import { Page, Locator, expect } from '@playwright/test';
import { BasePage } from './BasePage';

/**
 * Cart Page Object for Sauce Demo Shopify Store
 *
 * QE Assessment: sauce-demo.myshopify.com
 * Generated by: QE Queen Coordinator - qe-test-architect domain
 */
export class CartPage extends BasePage {
  // Cart container
  readonly cartContainer: Locator;
  readonly emptyCartMessage: Locator;

  // Cart items
  readonly cartItems: Locator;
  readonly cartItemTitles: Locator;
  readonly cartItemPrices: Locator;
  readonly cartItemQuantities: Locator;
  readonly cartItemImages: Locator;

  // Quantity controls (per item)
  readonly quantityInputs: Locator;
  readonly removeButtons: Locator;

  // Cart totals
  readonly subtotal: Locator;
  readonly discountSection: Locator;
  readonly taxesSection: Locator;
  readonly totalPrice: Locator;

  // Discount code
  readonly discountInput: Locator;
  readonly applyDiscountButton: Locator;
  readonly discountError: Locator;
  readonly discountSuccess: Locator;

  // Checkout buttons
  readonly checkoutButton: Locator;
  readonly continueShoppingLink: Locator;
  readonly updateCartButton: Locator;

  // Cart notes
  readonly cartNoteTextarea: Locator;

  // Shipping calculator
  readonly shippingCalculator: Locator;
  readonly countrySelect: Locator;
  readonly calculateShippingButton: Locator;

  constructor(page: Page) {
    super(page);

    // Cart container selectors (Shopify Simple theme)
    this.cartContainer = page.locator(
      '.cart, .cart-template, [data-cart-form], #cart'
    );
    this.emptyCartMessage = page.locator(
      '.cart--empty, .cart__empty, [data-empty-cart], :has-text("Your cart is empty")'
    );

    // Cart items selectors
    this.cartItems = page.locator(
      '.cart__row, .cart-item, [data-cart-item], tr[class*="cart"]'
    );
    this.cartItemTitles = page.locator(
      '.cart__row__product-title, .cart-item__title, [data-cart-item-title], td a[href*="/products/"]'
    );
    this.cartItemPrices = page.locator(
      '.cart__price, .cart-item__price, [data-cart-item-price]'
    );
    this.cartItemQuantities = page.locator(
      '.cart__quantity-selector input, .cart-item__quantity input, [data-cart-item-quantity]'
    );
    this.cartItemImages = page.locator(
      '.cart__image img, .cart-item__image img'
    );

    // Quantity and remove controls
    this.quantityInputs = page.locator(
      '.cart__quantity input, input[name*="quantity"], [data-quantity-input]'
    );
    this.removeButtons = page.locator(
      '.cart__remove, [data-cart-remove], a[href*="/cart/change"]:has-text("Remove"), button:has-text("Remove")'
    );

    // Totals selectors
    this.subtotal = page.locator(
      '.cart__subtotal, [data-cart-subtotal], .cart-subtotal__price'
    );
    this.discountSection = page.locator('.cart__discount, [data-cart-discount]');
    this.taxesSection = page.locator('.cart__taxes, [data-cart-taxes]');
    this.totalPrice = page.locator(
      '.cart__total, [data-cart-total], .cart-subtotal__price'
    ).first();

    // Discount code selectors
    this.discountInput = page.locator(
      'input[name="discount"], input[placeholder*="Discount"], #discount-code'
    );
    this.applyDiscountButton = page.locator(
      'button:has-text("Apply"), [data-apply-discount]'
    );
    this.discountError = page.locator('.discount-error, [data-discount-error]');
    this.discountSuccess = page.locator('.discount-success, [data-discount-success]');

    // Checkout selectors
    this.checkoutButton = page.locator(
      'button[name="checkout"], input[name="checkout"], [data-cart-checkout], a[href*="/checkout"]'
    ).first();
    this.continueShoppingLink = page.locator(
      'a:has-text("Continue shopping"), [data-continue-shopping]'
    );
    this.updateCartButton = page.locator(
      'button[name="update"], [data-update-cart], button:has-text("Update")'
    );

    // Cart notes
    this.cartNoteTextarea = page.locator(
      'textarea[name="note"], [data-cart-note]'
    );

    // Shipping calculator
    this.shippingCalculator = page.locator('.cart__shipping, [data-shipping-calculator]');
    this.countrySelect = page.locator('select[name*="country"], #address_country');
    this.calculateShippingButton = page.locator('button:has-text("Calculate"), [data-calculate-shipping]');
  }

  /**
   * Navigate to cart page
   */
  async goto(): Promise<void> {
    await super.goto('/cart');
    await this.waitForShopifyReady();
  }

  /**
   * Check if cart is empty
   */
  async isEmpty(): Promise<boolean> {
    // Check for empty message or zero items
    const emptyVisible = await this.emptyCartMessage.isVisible().catch(() => false);
    if (emptyVisible) return true;

    const itemCount = await this.cartItems.count();
    return itemCount === 0;
  }

  /**
   * Get number of items in cart
   */
  async getItemCount(): Promise<number> {
    return await this.cartItems.count();
  }

  /**
   * Get all item titles in cart
   */
  async getItemTitles(): Promise<string[]> {
    const titles = await this.cartItemTitles.allTextContents();
    return titles.map(t => t.trim());
  }

  /**
   * Get cart subtotal
   */
  async getSubtotal(): Promise<string> {
    return (await this.subtotal.textContent() || '').trim();
  }

  /**
   * Get cart total
   */
  async getTotal(): Promise<string> {
    return (await this.totalPrice.textContent() || '').trim();
  }

  /**
   * Update quantity for item at index
   */
  async updateQuantity(index: number, quantity: number): Promise<void> {
    const input = this.quantityInputs.nth(index);
    await input.fill(quantity.toString());

    // Submit update if there's an update button
    if (await this.updateCartButton.isVisible()) {
      await this.updateCartButton.click();
    } else {
      // Some themes auto-update on blur
      await input.blur();
    }

    // Wait for cart to update
    await this.page.waitForResponse(
      resp => resp.url().includes('/cart') && resp.status() === 200,
      { timeout: 5000 }
    ).catch(() => {});
  }

  /**
   * Remove item at index
   */
  async removeItem(index: number): Promise<void> {
    await this.removeButtons.nth(index).click();

    // Wait for cart to update
    await this.page.waitForResponse(
      resp => resp.url().includes('/cart') && resp.status() === 200,
      { timeout: 5000 }
    ).catch(() => {});
  }

  /**
   * Remove all items from cart
   */
  async clearCart(): Promise<void> {
    while (!(await this.isEmpty())) {
      await this.removeItem(0);
      await this.page.waitForTimeout(500);
    }
  }

  /**
   * Apply a discount code
   */
  async applyDiscount(code: string): Promise<void> {
    await this.discountInput.fill(code);
    await this.applyDiscountButton.click();
    await this.page.waitForTimeout(1000);
  }

  /**
   * Add note to cart
   */
  async addNote(note: string): Promise<void> {
    await this.cartNoteTextarea.fill(note);
  }

  /**
   * Proceed to checkout
   */
  async proceedToCheckout(): Promise<void> {
    await this.checkoutButton.click();
    // Wait for checkout page (Shopify hosted checkout)
    await this.page.waitForURL(/.*checkout.*/, { timeout: 30000 });
  }

  /**
   * Continue shopping
   */
  async continueShopping(): Promise<void> {
    await this.continueShoppingLink.click();
    await this.page.waitForURL(/.*(?!cart).*/);
  }

  /**
   * Assert cart page loaded correctly
   */
  async assertCartPageLoaded(): Promise<void> {
    await this.assertPageLoaded();
    await expect(this.page).toHaveURL(/.*\/cart.*/);
  }

  /**
   * Assert cart has items
   */
  async assertHasItems(): Promise<void> {
    const empty = await this.isEmpty();
    expect(empty).toBe(false);

    const count = await this.getItemCount();
    expect(count).toBeGreaterThan(0);
  }

  /**
   * Assert cart is empty
   */
  async assertIsEmpty(): Promise<void> {
    const empty = await this.isEmpty();
    expect(empty).toBe(true);
  }

  /**
   * Assert specific product is in cart
   */
  async assertProductInCart(productName: string): Promise<void> {
    const titles = await this.getItemTitles();
    const found = titles.some(t => t.toLowerCase().includes(productName.toLowerCase()));
    expect(found).toBe(true);
  }
}
