import { Page, Locator, expect } from '@playwright/test';

/**
 * Checkout Page Object for Sauce Demo Shopify Store
 *
 * Note: Shopify checkout is hosted on checkout.shopify.com domain
 * This page object handles the Shopify-hosted checkout flow
 *
 * QE Assessment: sauce-demo.myshopify.com
 * Generated by: QE Queen Coordinator - qe-test-architect domain
 */
export class CheckoutPage {
  readonly page: Page;

  // Checkout steps indicator
  readonly breadcrumbs: Locator;
  readonly stepIndicator: Locator;

  // Contact information
  readonly emailInput: Locator;
  readonly phoneInput: Locator;
  readonly newsletterCheckbox: Locator;

  // Shipping address
  readonly firstNameInput: Locator;
  readonly lastNameInput: Locator;
  readonly addressInput: Locator;
  readonly address2Input: Locator;
  readonly cityInput: Locator;
  readonly countrySelect: Locator;
  readonly provinceSelect: Locator;
  readonly postalCodeInput: Locator;

  // Shipping method
  readonly shippingMethods: Locator;
  readonly selectedShippingMethod: Locator;

  // Payment section
  readonly paymentSection: Locator;
  readonly creditCardRadio: Locator;
  readonly paypalRadio: Locator;
  readonly cardNumberInput: Locator;
  readonly cardNameInput: Locator;
  readonly cardExpiryInput: Locator;
  readonly cardCVVInput: Locator;

  // Billing address
  readonly sameAsShippingCheckbox: Locator;
  readonly billingAddressSection: Locator;

  // Order summary
  readonly orderSummary: Locator;
  readonly orderItems: Locator;
  readonly subtotalDisplay: Locator;
  readonly shippingDisplay: Locator;
  readonly taxDisplay: Locator;
  readonly totalDisplay: Locator;

  // Discount code
  readonly discountInput: Locator;
  readonly applyDiscountButton: Locator;
  readonly discountApplied: Locator;

  // Navigation buttons
  readonly continueButton: Locator;
  readonly returnToCartLink: Locator;
  readonly returnToShippingLink: Locator;
  readonly payNowButton: Locator;

  // Error handling
  readonly errorBanner: Locator;
  readonly fieldErrors: Locator;

  // Express checkout
  readonly expressCheckout: Locator;
  readonly shopPayButton: Locator;
  readonly applePayButton: Locator;
  readonly googlePayButton: Locator;

  constructor(page: Page) {
    this.page = page;

    // Step indicators
    this.breadcrumbs = page.locator('.breadcrumb, [data-step], .step__footer');
    this.stepIndicator = page.locator('.step, [data-checkout-step]');

    // Contact info (Shopify checkout selectors)
    this.emailInput = page.locator(
      '#email, input[name="email"], [data-checkout-email], input[placeholder*="Email"]'
    );
    this.phoneInput = page.locator(
      '#phone, input[name="phone"], [data-checkout-phone], input[type="tel"]'
    );
    this.newsletterCheckbox = page.locator(
      '#marketing_opt_in, input[name*="marketing"], [data-marketing-opt-in]'
    );

    // Shipping address selectors
    this.firstNameInput = page.locator(
      '#first_name, input[name*="first_name"], [autocomplete="given-name"]'
    );
    this.lastNameInput = page.locator(
      '#last_name, input[name*="last_name"], [autocomplete="family-name"]'
    );
    this.addressInput = page.locator(
      '#address1, input[name*="address1"], [autocomplete="address-line1"]'
    );
    this.address2Input = page.locator(
      '#address2, input[name*="address2"], [autocomplete="address-line2"]'
    );
    this.cityInput = page.locator(
      '#city, input[name*="city"], [autocomplete="address-level2"]'
    );
    this.countrySelect = page.locator(
      '#country, select[name*="country"], [autocomplete="country"]'
    );
    this.provinceSelect = page.locator(
      '#province, select[name*="province"], [autocomplete="address-level1"]'
    );
    this.postalCodeInput = page.locator(
      '#zip, input[name*="zip"], [autocomplete="postal-code"]'
    );

    // Shipping method
    this.shippingMethods = page.locator(
      '.radio-wrapper, [data-shipping-method], .content-box__row'
    );
    this.selectedShippingMethod = page.locator(
      'input[name="shipping_rate"]:checked, [data-shipping-method].checked'
    );

    // Payment section
    this.paymentSection = page.locator('.section--payment, [data-payment-section]');
    this.creditCardRadio = page.locator('input[value*="credit"], [data-payment-method="credit_card"]');
    this.paypalRadio = page.locator('input[value*="paypal"], [data-payment-method="paypal"]');

    // Card inputs (within Shopify's iframe)
    this.cardNumberInput = page.frameLocator('iframe[title*="card number"]').locator('input');
    this.cardNameInput = page.locator('input[name="name"], #name, [autocomplete="cc-name"]');
    this.cardExpiryInput = page.frameLocator('iframe[title*="expiry"]').locator('input');
    this.cardCVVInput = page.frameLocator('iframe[title*="security"]').locator('input');

    // Billing address
    this.sameAsShippingCheckbox = page.locator(
      '#billing_address_same_as_shipping, input[name*="same_as_shipping"]'
    );
    this.billingAddressSection = page.locator('.section--billing-address, [data-billing-address]');

    // Order summary
    this.orderSummary = page.locator('.order-summary, [data-order-summary]');
    this.orderItems = page.locator('.product, [data-order-summary-product]');
    this.subtotalDisplay = page.locator('[data-checkout-subtotal], .total-line--subtotal');
    this.shippingDisplay = page.locator('[data-checkout-shipping], .total-line--shipping');
    this.taxDisplay = page.locator('[data-checkout-tax], .total-line--taxes');
    this.totalDisplay = page.locator('[data-checkout-total], .total-line--total .payment-due__price');

    // Discount
    this.discountInput = page.locator(
      '#discount, input[name="discount"], [data-discount-field]'
    );
    this.applyDiscountButton = page.locator(
      '#apply-discount, button:has-text("Apply"), [data-apply-discount]'
    );
    this.discountApplied = page.locator('.reduction-code, [data-discount-applied]');

    // Navigation
    this.continueButton = page.locator(
      '#continue_button, button:has-text("Continue"), [data-continue-button]'
    );
    this.returnToCartLink = page.locator('a:has-text("Return to cart"), [data-return-to-cart]');
    this.returnToShippingLink = page.locator('a:has-text("Return to shipping")');
    this.payNowButton = page.locator(
      '#complete-purchase, button:has-text("Pay now"), [data-pay-button]'
    );

    // Errors
    this.errorBanner = page.locator('.notice--error, [data-checkout-error], .banner--error');
    this.fieldErrors = page.locator('.field__message--error, .error-message');

    // Express checkout
    this.expressCheckout = page.locator('.express-checkout, [data-express-checkout]');
    this.shopPayButton = page.locator('[data-shopify-pay], .shopify-pay-button');
    this.applePayButton = page.locator('[data-apple-pay], .apple-pay-button');
    this.googlePayButton = page.locator('[data-google-pay], .google-pay-button');
  }

  /**
   * Wait for checkout page to load
   */
  async waitForCheckoutReady(): Promise<void> {
    await this.page.waitForURL(/.*checkout.*/, { timeout: 30000 });
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Fill contact information
   */
  async fillContactInfo(email: string, phone?: string): Promise<void> {
    await this.emailInput.fill(email);
    if (phone) {
      await this.phoneInput.fill(phone);
    }
  }

  /**
   * Fill shipping address
   */
  async fillShippingAddress(address: {
    firstName: string;
    lastName: string;
    address: string;
    address2?: string;
    city: string;
    country: string;
    province?: string;
    postalCode: string;
  }): Promise<void> {
    await this.firstNameInput.fill(address.firstName);
    await this.lastNameInput.fill(address.lastName);
    await this.addressInput.fill(address.address);

    if (address.address2) {
      await this.address2Input.fill(address.address2);
    }

    await this.cityInput.fill(address.city);
    await this.countrySelect.selectOption({ label: address.country });

    // Wait for province options to load if country was selected
    await this.page.waitForTimeout(500);

    if (address.province) {
      await this.provinceSelect.selectOption({ label: address.province });
    }

    await this.postalCodeInput.fill(address.postalCode);
  }

  /**
   * Continue to next step
   */
  async continueToNextStep(): Promise<void> {
    await this.continueButton.click();
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Select shipping method by index
   */
  async selectShippingMethod(index: number = 0): Promise<void> {
    const methods = this.shippingMethods.locator('input[type="radio"]');
    await methods.nth(index).click();
  }

  /**
   * Apply discount code
   */
  async applyDiscount(code: string): Promise<void> {
    // Expand discount section if collapsed
    const discountToggle = this.page.locator('[data-discount-toggle], .reduction-code__text');
    if (await discountToggle.isVisible()) {
      await discountToggle.click();
    }

    await this.discountInput.fill(code);
    await this.applyDiscountButton.click();
    await this.page.waitForTimeout(1000);
  }

  /**
   * Get order total
   */
  async getOrderTotal(): Promise<string> {
    return (await this.totalDisplay.textContent() || '').trim();
  }

  /**
   * Get number of items in order
   */
  async getOrderItemCount(): Promise<number> {
    return await this.orderItems.count();
  }

  /**
   * Return to cart
   */
  async returnToCart(): Promise<void> {
    await this.returnToCartLink.click();
    await this.page.waitForURL(/.*cart.*/);
  }

  /**
   * Check if there are validation errors
   */
  async hasErrors(): Promise<boolean> {
    return await this.errorBanner.isVisible() || await this.fieldErrors.first().isVisible();
  }

  /**
   * Get all error messages
   */
  async getErrorMessages(): Promise<string[]> {
    const errors: string[] = [];

    if (await this.errorBanner.isVisible()) {
      errors.push(await this.errorBanner.textContent() || '');
    }

    const fieldErrorTexts = await this.fieldErrors.allTextContents();
    errors.push(...fieldErrorTexts);

    return errors.filter(e => e.trim());
  }

  /**
   * Assert checkout page loaded
   */
  async assertCheckoutLoaded(): Promise<void> {
    await expect(this.page).toHaveURL(/.*checkout.*/);
    await expect(this.emailInput.or(this.firstNameInput).first()).toBeVisible({ timeout: 10000 });
  }

  /**
   * Assert on shipping step
   */
  async assertOnShippingStep(): Promise<void> {
    await expect(this.shippingMethods.first()).toBeVisible();
  }

  /**
   * Assert on payment step
   */
  async assertOnPaymentStep(): Promise<void> {
    await expect(this.paymentSection).toBeVisible();
  }
}
