/**
 * Page Object Model Index
 * Export all page objects for easy importing
 *
 * QE Assessment: sauce-demo.myshopify.com
 * Generated by: QE Queen Coordinator
 */

export { BasePage } from './BasePage';
export { HomePage } from './HomePage';
export { ProductPage } from './ProductPage';
export { CartPage } from './CartPage';
export { CheckoutPage } from './CheckoutPage';
