/**
 * Learning System Initialization
 *
 * Initializes the Nightly-Learner system including:
 * - ExperienceCapture singleton
 * - SleepScheduler for automated learning cycles
 * - Learning configuration persistence
 *
 * @module cli/init/learning-init
 */

import * as path from 'path';
import * as fs from 'fs-extra';
import { FleetConfig } from '../../types';
import { Logger } from '../../utils/Logger';

export interface LearningInitConfig {
  /** Schedule mode: 'idle', 'time', or 'hybrid' */
  mode?: 'idle' | 'time' | 'hybrid';
  /** Hour to run nightly learning (0-23). Default: 2 */
  startHour?: number;
  /** Duration of learning cycle in minutes. Default: 60 */
  durationMinutes?: number;
  /** Enable learning on init. Default: true */
  enabled?: boolean;
}

const DEFAULT_LEARNING_CONFIG: LearningInitConfig = {
  mode: 'hybrid',
  startHour: 2,
  durationMinutes: 60,
  enabled: true,
};

/**
 * Initialize the learning system
 *
 * Sets up:
 * 1. Learning configuration file
 * 2. Required database tables (via ExperienceCapture)
 * 3. Scheduler configuration for nightly runs
 */
export async function initializeLearningSystem(
  fleetConfig: FleetConfig,
  learningConfig?: LearningInitConfig
): Promise<void> {
  const logger = Logger.getInstance();
  const config = { ...DEFAULT_LEARNING_CONFIG, ...learningConfig };

  logger.info('[LearningInit] Initializing Nightly-Learner system', config);

  const baseDir = path.join(process.cwd(), '.agentic-qe');

  // 1. Ensure base directory exists
  await fs.ensureDir(baseDir);

  // 2. Create learning configuration file
  const learningConfigPath = path.join(baseDir, 'learning-config.json');

  const fullConfig = {
    version: '1.0.0',
    enabled: config.enabled,
    scheduler: {
      mode: config.mode,
      schedule: {
        startHour: config.startHour,
        durationMinutes: config.durationMinutes,
        daysOfWeek: [0, 1, 2, 3, 4, 5, 6], // Every day
      },
      learningBudget: {
        maxPatternsPerCycle: 50,
        maxAgentsPerCycle: 5,
        maxDurationMs: 3600000, // 1 hour
      },
    },
    capture: {
      bufferSize: 100,
      flushInterval: 30000, // 30 seconds
    },
    metrics: {
      retentionDays: 30,
      alertThresholds: {
        successRateDrop: 15,
        completionTimeIncrease: 20,
        coverageDrop: 15,
      },
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  await fs.writeJson(learningConfigPath, fullConfig, { spaces: 2 });
  logger.info('[LearningInit] Created learning configuration', { path: learningConfigPath });

  // 3. Initialize ExperienceCapture (creates database tables)
  // Note: We only verify the database schema is created, then stop the capture
  // to allow the init process to exit cleanly. The capture will be started
  // again when agents actually run.
  try {
    const { ExperienceCapture } = await import('../../learning/capture/ExperienceCapture');
    const capture = await ExperienceCapture.getSharedInstance({
      bufferSize: config.enabled ? 100 : 0,
      flushInterval: 30000,
    });

    // Get stats to verify initialization
    const stats = capture.getStats();
    logger.info('[LearningInit] ExperienceCapture initialized', {
      totalCaptured: stats.totalCaptured,
      bufferSize: stats.bufferSize,
    });

    // Stop the capture service to allow process to exit
    // It will be restarted when agents run
    await capture.stop();
    ExperienceCapture.resetInstance();
  } catch (error) {
    logger.warn('[LearningInit] ExperienceCapture initialization deferred', {
      error: error instanceof Error ? error.message : String(error),
    });
  }

  // 4. Create scheduler startup script
  const schedulerScriptPath = path.join(baseDir, 'start-learning.js');
  const schedulerScript = `#!/usr/bin/env node
/**
 * Nightly-Learner Startup Script
 * Generated by aqe init
 *
 * Run this script to start the learning scheduler:
 *   node .agentic-qe/start-learning.js
 *
 * Or add to your application startup.
 */

const path = require('path');

async function startLearning() {
  try {
    // Load configuration
    const config = require('./learning-config.json');

    if (!config.enabled) {
      console.log('[Nightly-Learner] Learning is disabled in config');
      return;
    }

    // Import scheduler
    const { SleepScheduler } = require('agentic-qe/dist/learning/scheduler/SleepScheduler');

    // Create and start scheduler
    const scheduler = new SleepScheduler({
      mode: config.scheduler.mode,
      schedule: config.scheduler.schedule,
      learningBudget: config.scheduler.learningBudget,
    });

    scheduler.on('scheduler:started', (state) => {
      console.log('[Nightly-Learner] Scheduler started:', state.mode);
    });

    scheduler.on('sleep:start', (cycle) => {
      console.log('[Nightly-Learner] Learning cycle started');
    });

    scheduler.on('sleep:end', (summary) => {
      console.log('[Nightly-Learner] Learning cycle complete:', {
        patternsDiscovered: summary.patternsDiscovered,
        agentsProcessed: summary.agentsProcessed.length,
      });
    });

    scheduler.on('error', (error) => {
      console.error('[Nightly-Learner] Error:', error);
    });

    await scheduler.start();
    console.log('[Nightly-Learner] System running. Press Ctrl+C to stop.');

    // Handle graceful shutdown
    process.on('SIGINT', async () => {
      console.log('\\n[Nightly-Learner] Shutting down...');
      await scheduler.stop();
      process.exit(0);
    });

  } catch (error) {
    console.error('[Nightly-Learner] Failed to start:', error);
    process.exit(1);
  }
}

startLearning();
`;

  await fs.writeFile(schedulerScriptPath, schedulerScript);
  await fs.chmod(schedulerScriptPath, 0o755);
  logger.info('[LearningInit] Created scheduler startup script', { path: schedulerScriptPath });

  logger.info('[LearningInit] Learning system initialization complete');
}

/**
 * Check if learning system is initialized
 */
export async function isLearningInitialized(): Promise<boolean> {
  const configPath = path.join(process.cwd(), '.agentic-qe', 'learning-config.json');
  return fs.pathExists(configPath);
}

/**
 * Get learning configuration
 */
export async function getLearningConfig(): Promise<LearningInitConfig | null> {
  const configPath = path.join(process.cwd(), '.agentic-qe', 'learning-config.json');

  if (await fs.pathExists(configPath)) {
    try {
      const config = await fs.readJson(configPath);
      return {
        mode: config.scheduler?.mode,
        startHour: config.scheduler?.schedule?.startHour,
        durationMinutes: config.scheduler?.schedule?.durationMinutes,
        enabled: config.enabled,
      };
    } catch {
      return null;
    }
  }

  return null;
}
