import { test, expect } from '@playwright/test';
import { ProductPage, HomePage } from '../pages';
import { TestData } from '../fixtures/test-data';

/**
 * Product Page E2E Tests
 * Test Suite: Product Viewing and Add to Cart Flow
 *
 * QE Assessment: sauce-demo.myshopify.com
 * Generated by: QE Queen Coordinator - qe-test-architect domain
 *
 * Coverage:
 * - Product page loading
 * - Product information display
 * - Variant selection
 * - Quantity adjustment
 * - Add to cart functionality
 * - Image gallery
 */

test.describe('Product Page - View and Add to Cart', () => {
  let productPage: ProductPage;

  test.beforeEach(async ({ page }) => {
    productPage = new ProductPage(page);
  });

  test.describe('Product Page Loading', () => {
    test('should load product page via direct URL', async ({ page }) => {
      // Navigate to a known product
      await page.goto('/collections/frontpage');
      await page.locator('[class*="product"] a, .grid-product a').first().click();

      await productPage.assertProductPageLoaded();
    });

    test('should load product page from home page navigation', async ({ page }) => {
      const homePage = new HomePage(page);
      await homePage.goto();
      await homePage.clickFirstProduct();

      await productPage.assertProductPageLoaded();
    });

    test('should display product title', async ({ page }) => {
      await page.goto('/collections/frontpage');
      await page.locator('[class*="product"] a, .grid-product a').first().click();

      const title = await productPage.getTitle();
      expect(title).toBeTruthy();
      expect(title.length).toBeGreaterThan(0);
    });

    test('should display product price', async ({ page }) => {
      await page.goto('/collections/frontpage');
      await page.locator('[class*="product"] a, .grid-product a').first().click();

      const price = await productPage.getPrice();
      expect(price).toMatch(/£\d+/);
    });
  });

  test.describe('Product Information', () => {
    test.beforeEach(async ({ page }) => {
      await page.goto('/collections/frontpage');
      await page.locator('[class*="product"] a, .grid-product a').first().click();
      await productPage.assertProductPageLoaded();
    });

    test('should display product images', async () => {
      await productPage.assertImagesLoaded();
    });

    test('should display add to cart button', async () => {
      await expect(productPage.addToCartButton).toBeVisible();
      await expect(productPage.addToCartButton).toBeEnabled();
    });

    test('should display quantity input', async () => {
      await expect(productPage.quantityInput).toBeVisible();

      const value = await productPage.quantityInput.inputValue();
      expect(parseInt(value)).toBe(1);
    });
  });

  test.describe('Quantity Adjustment', () => {
    test.beforeEach(async ({ page }) => {
      await page.goto('/collections/frontpage');
      await page.locator('[class*="product"] a, .grid-product a').first().click();
      await productPage.assertProductPageLoaded();
    });

    test('should allow changing quantity via input', async () => {
      await productPage.setQuantity(3);

      const value = await productPage.quantityInput.inputValue();
      expect(parseInt(value)).toBe(3);
    });

    test('should increase quantity with + button', async () => {
      const initialValue = parseInt(await productPage.quantityInput.inputValue());

      await productPage.increaseQuantity(2);

      const newValue = parseInt(await productPage.quantityInput.inputValue());
      expect(newValue).toBe(initialValue + 2);
    });

    test('should not allow quantity below 1', async () => {
      await productPage.setQuantity(0);
      await productPage.addToCartButton.click();

      // Should either reset to 1 or show error
      const value = await productPage.quantityInput.inputValue();
      expect(parseInt(value)).toBeGreaterThanOrEqual(1);
    });
  });

  test.describe('Add to Cart Functionality', () => {
    test.beforeEach(async ({ page }) => {
      await page.goto('/collections/frontpage');
      await page.locator('[class*="product"] a, .grid-product a').first().click();
      await productPage.assertProductPageLoaded();
    });

    test('should add product to cart successfully', async ({ page }) => {
      const initialCount = await productPage.getCartCount();

      await productPage.addToCart();
      await productPage.assertAddedToCart();

      const newCount = await productPage.getCartCount();
      expect(newCount).toBeGreaterThan(initialCount);
    });

    test('should add multiple quantities to cart', async ({ page }) => {
      await productPage.setQuantity(2);
      await productPage.addToCart();

      await productPage.assertAddedToCart();
    });

    test('should show cart notification after adding', async ({ page }) => {
      await productPage.addToCart();

      // Either notification appears or cart count updates
      const notificationVisible = await productPage.addedToCartNotification
        .isVisible({ timeout: 3000 })
        .catch(() => false);

      const cartUpdated = (await productPage.getCartCount()) > 0;

      expect(notificationVisible || cartUpdated).toBe(true);
    });

    test('should persist cart after page reload', async ({ page }) => {
      await productPage.addToCart();

      const countBeforeReload = await productPage.getCartCount();

      await page.reload();
      await productPage.waitForShopifyReady();

      const countAfterReload = await productPage.getCartCount();
      expect(countAfterReload).toBe(countBeforeReload);
    });
  });

  test.describe('Navigation from Product Page', () => {
    test.beforeEach(async ({ page }) => {
      await page.goto('/collections/frontpage');
      await page.locator('[class*="product"] a, .grid-product a').first().click();
      await productPage.assertProductPageLoaded();
    });

    test('should navigate to cart from product page', async ({ page }) => {
      await productPage.addToCart();
      await productPage.openCart();

      await expect(page).toHaveURL(/.*\/cart.*/);
    });

    test('should navigate back to catalog', async ({ page }) => {
      await productPage.goToCatalog();

      await expect(page).toHaveURL(/.*\/collections\/.*/);
    });

    test('should allow browser back navigation', async ({ page }) => {
      const productUrl = page.url();

      await productPage.goToCatalog();
      await page.goBack();

      await expect(page).toHaveURL(productUrl);
    });
  });

  test.describe('Product Page Edge Cases', () => {
    test('should handle non-existent product gracefully', async ({ page }) => {
      const response = await page.goto('/products/this-product-does-not-exist-xyz');

      // Should either 404 or redirect
      expect(response?.status()).toBeGreaterThanOrEqual(200);
    });

    test('should handle rapid add-to-cart clicks', async ({ page }) => {
      await page.goto('/collections/frontpage');
      await page.locator('[class*="product"] a, .grid-product a').first().click();
      await productPage.assertProductPageLoaded();

      // Rapid clicks
      await productPage.addToCartButton.click();
      await productPage.addToCartButton.click();
      await productPage.addToCartButton.click();

      // Should not cause errors
      await page.waitForTimeout(2000);
      await expect(page).not.toHaveTitle(/error/i);
    });
  });
});
