/**
 * Agentic QE v3 - Lifecycle HTML Report Generator
 * Produces a self-contained HTML report from ActionOrchestrator RunResult.
 * No external dependencies — inline CSS, no JS frameworks.
 *
 * Generic: works with any lifecycle run, not tied to a specific client.
 */

import { writeFile, mkdir } from 'fs/promises';
import { join } from 'path';
import type { RunResult, StageResult } from './action-types';

// ============================================================================
// Public API
// ============================================================================

export interface ReportOptions {
  /** Report title shown in the header. */
  title?: string;
  /** File name prefix (default: 'lifecycle'). */
  filenamePrefix?: string;
  /** Output directory (default: cwd/v3/tests/reports). */
  outputDir?: string;
}

/**
 * Generate a self-contained HTML report for a lifecycle run.
 * @returns The absolute path to the generated report file.
 */
export async function generateLifecycleReport(
  result: RunResult,
  runId: string,
  options: ReportOptions = {},
): Promise<string> {
  const dir = options.outputDir ?? join(process.cwd(), 'v3', 'tests', 'reports');
  await mkdir(dir, { recursive: true });

  const prefix = options.filenamePrefix ?? 'lifecycle';
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
  const filename = `${prefix}-${runId}-${timestamp}.html`;
  const filePath = join(dir, filename);

  const title = options.title ?? 'Lifecycle Report';
  const html = buildHtml(result, runId, title);
  await writeFile(filePath, html, 'utf-8');

  return filePath;
}

// ============================================================================
// HTML Builder
// ============================================================================

function buildHtml(result: RunResult, runId: string, title: string): string {
  const now = new Date().toISOString();
  const totalStages = result.stages.length;
  const passedStages = result.stages.filter((s) => s.overallSuccess).length;
  const failedStages = result.stages.filter((s) => !s.overallSuccess).length;
  const totalDuration = (result.totalDurationMs / 1000).toFixed(1);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>${title} — ${runId}</title>
<style>
${CSS}
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>${title}</h1>
    <div class="meta">
      <span><strong>Order:</strong> ${runId}</span>
      <span><strong>Date:</strong> ${now}</span>
      <span class="badge ${result.overallSuccess ? 'pass' : 'fail'}">${result.overallSuccess ? 'PASS' : 'FAIL'}</span>
    </div>
  </header>

  <section class="summary">
    <div class="stat"><span class="num">${totalStages}</span><span class="label">Stages</span></div>
    <div class="stat pass"><span class="num">${passedStages}</span><span class="label">Passed</span></div>
    <div class="stat fail"><span class="num">${failedStages}</span><span class="label">Failed</span></div>
    <div class="stat"><span class="num">${result.totalChecks}</span><span class="label">Checks</span></div>
    <div class="stat"><span class="num">${totalDuration}s</span><span class="label">Duration</span></div>
  </section>

  <section class="stages">
    <h2>Stage Results</h2>
    <table>
      <thead>
        <tr><th>#</th><th>Stage</th><th>Action</th><th>Poll</th><th>Verify</th><th>Duration</th><th>Status</th></tr>
      </thead>
      <tbody>
${result.stages.map((s, i) => stageRow(s, i + 1)).join('\n')}
      </tbody>
    </table>
  </section>

  <section class="details">
    <h2>Step Details</h2>
${result.stages.map((s) => stageDetails(s)).join('\n')}
  </section>

  <footer>
    <p>Generated by <strong>Agentic QE v3</strong> — Action Orchestrator</p>
  </footer>
</div>
</body>
</html>`;
}

// ============================================================================
// HTML Fragments
// ============================================================================

function stageRow(stage: StageResult, index: number): string {
  const status = stage.overallSuccess ? 'pass' : 'fail';
  const actionStatus = stage.action.success ? 'OK' : 'FAIL';
  const pollStatus = stage.poll.success ? 'OK' : 'FAIL';
  const verifyStr = `${stage.verification.passed}/${stage.verification.passed + stage.verification.failed + stage.verification.skipped}`;
  const duration = (stage.durationMs / 1000).toFixed(1) + 's';

  return `        <tr class="${status}">
          <td>${index}</td>
          <td>${stage.stageName}</td>
          <td class="${stage.action.success ? 'pass' : 'fail'}">${actionStatus}</td>
          <td class="${stage.poll.success ? 'pass' : 'fail'}">${pollStatus}</td>
          <td>${verifyStr}</td>
          <td>${duration}</td>
          <td><span class="badge ${status}">${stage.overallSuccess ? 'PASS' : 'FAIL'}</span></td>
        </tr>`;
}

function stageDetails(stage: StageResult): string {
  const hasSteps = stage.verification.steps.length > 0;
  const hasActionError = !stage.action.success && stage.action.error;
  const hasPollError = !stage.poll.success && stage.poll.error;

  if (!hasSteps && !hasActionError && !hasPollError) return '';

  const errorRows: string[] = [];
  if (hasActionError) {
    errorRows.push(`      <div class="step fail">
        <div class="step-header">
          <span class="badge fail">FAIL</span>
          <strong>Action</strong>
          <span class="dur">${stage.action.durationMs}ms</span>
          <span class="err">${escapeHtml(stage.action.error!)}</span>
        </div>
      </div>`);
  }
  if (hasPollError) {
    errorRows.push(`      <div class="step fail">
        <div class="step-header">
          <span class="badge fail">FAIL</span>
          <strong>Poll</strong>
          <span class="dur">${stage.poll.durationMs}ms</span>
          <span class="err">${escapeHtml(stage.poll.error!)}</span>
        </div>
      </div>`);
  }

  const stepRows = stage.verification.steps.map((s) => {
    const r = s.result;
    const status = r.success ? 'pass' : 'fail';
    const checks = (r.checks ?? [])
      .map((c) => `<li class="${c.passed ? 'check-pass' : 'check-fail'}">${c.name}: expected ${c.expected}, got ${c.actual}</li>`)
      .join('');

    return `      <div class="step ${status}">
        <div class="step-header">
          <span class="badge ${status}">${r.success ? 'PASS' : 'FAIL'}</span>
          <strong>${s.stepId}</strong>
          <span class="dur">${r.durationMs}ms</span>
          ${r.error ? `<span class="err">${escapeHtml(r.error)}</span>` : ''}
        </div>
        ${checks ? `<ul class="checks">${checks}</ul>` : ''}
      </div>`;
  }).join('\n');

  return `    <div class="stage-detail">
      <h3>${stage.stageName} <span class="stage-id">(${stage.stageId})</span></h3>
${[...errorRows, stepRows].join('\n')}
    </div>`;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// ============================================================================
// Embedded CSS
// ============================================================================

const CSS = `
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; color: #333; line-height: 1.6; }
.container { max-width: 1100px; margin: 2rem auto; padding: 0 1rem; }
header { background: #1a1a2e; color: #fff; padding: 1.5rem 2rem; border-radius: 8px 8px 0 0; }
header h1 { font-size: 1.4rem; margin-bottom: 0.5rem; }
.meta { display: flex; gap: 1.5rem; align-items: center; font-size: 0.9rem; opacity: 0.9; flex-wrap: wrap; }
.badge { padding: 2px 10px; border-radius: 4px; font-size: 0.8rem; font-weight: 700; text-transform: uppercase; }
.badge.pass { background: #22c55e; color: #fff; }
.badge.fail { background: #ef4444; color: #fff; }
.summary { display: flex; gap: 1rem; padding: 1.5rem 2rem; background: #fff; border-bottom: 1px solid #e5e5e5; flex-wrap: wrap; }
.stat { text-align: center; min-width: 80px; }
.stat .num { display: block; font-size: 1.8rem; font-weight: 700; }
.stat .label { font-size: 0.75rem; text-transform: uppercase; color: #888; }
.stat.pass .num { color: #22c55e; }
.stat.fail .num { color: #ef4444; }
.stages, .details { background: #fff; padding: 1.5rem 2rem; border-bottom: 1px solid #e5e5e5; }
.stages h2, .details h2 { font-size: 1.1rem; margin-bottom: 1rem; }
table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
th { text-align: left; padding: 8px 12px; background: #f0f0f0; border-bottom: 2px solid #ddd; }
td { padding: 8px 12px; border-bottom: 1px solid #eee; }
tr.pass td:first-child { border-left: 3px solid #22c55e; }
tr.fail td:first-child { border-left: 3px solid #ef4444; }
td.pass { color: #16a34a; }
td.fail { color: #dc2626; }
.stage-detail { margin-bottom: 1.5rem; }
.stage-detail h3 { font-size: 1rem; margin-bottom: 0.5rem; }
.stage-id { color: #888; font-weight: 400; font-size: 0.85rem; }
.step { padding: 0.5rem 0.75rem; margin-bottom: 0.5rem; border-radius: 4px; border-left: 3px solid #ddd; }
.step.pass { border-left-color: #22c55e; background: #f0fdf4; }
.step.fail { border-left-color: #ef4444; background: #fef2f2; }
.step-header { display: flex; gap: 0.75rem; align-items: center; flex-wrap: wrap; }
.dur { color: #888; font-size: 0.8rem; }
.err { color: #dc2626; font-size: 0.8rem; }
.checks { list-style: none; margin-top: 0.4rem; padding-left: 1rem; font-size: 0.85rem; }
.check-pass::before { content: "✓ "; color: #22c55e; }
.check-fail::before { content: "✗ "; color: #ef4444; }
footer { background: #fff; padding: 1rem 2rem; border-radius: 0 0 8px 8px; text-align: center; font-size: 0.8rem; color: #888; }
`;
