/**
 * Test: Assets Phase - Version Upgrade Detection
 *
 * Verifies that:
 * 1. detectVersionUpgrade correctly identifies version changes
 * 2. Auto mode with version change triggers asset updates
 * 3. Skills and agents are overwritten when upgrading
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { existsSync, mkdirSync, writeFileSync, rmSync } from 'fs';
import { join } from 'path';
import { AssetsPhase } from '../../../src/init/phases/09-assets.js';
import type { InitContext } from '../../../src/init/phases/phase-interface.js';
import type { AQEInitConfig } from '../../../src/init/types.js';

describe('AssetsPhase - Version Upgrade Detection', () => {
  const testDir = join(process.cwd(), '.test-assets-phase');
  const phase = new AssetsPhase() as any; // Access private methods

  beforeEach(() => {
    // Create test directory structure
    if (existsSync(testDir)) {
      rmSync(testDir, { recursive: true });
    }
    mkdirSync(join(testDir, '.agentic-qe'), { recursive: true });
  });

  afterEach(() => {
    // Cleanup
    if (existsSync(testDir)) {
      rmSync(testDir, { recursive: true });
    }
  });

  const createMockContext = (version: string, options: Partial<InitContext['options']> = {}): InitContext => ({
    projectRoot: testDir,
    options: {
      autoMode: false,
      upgrade: false,
      ...options,
    },
    config: {
      version,
      project: { name: 'test', root: testDir, type: 'single' },
      skills: { install: true, installV2: true, installV3: true, overwrite: false },
    } as AQEInitConfig,
    services: {
      log: () => {},
      warn: () => {},
      error: () => {},
    },
    phaseResults: new Map(),
  });

  describe('detectVersionUpgrade', () => {
    it('should return false when no config exists', () => {
      const context = createMockContext('3.5.3');
      const result = phase.detectVersionUpgrade(context);
      expect(result).toBe(false);
    });

    it('should return false when versions match', () => {
      // Create existing config with same version
      const configPath = join(testDir, '.agentic-qe', 'config.yaml');
      writeFileSync(configPath, 'version: "3.5.3"\n', 'utf-8');

      const context = createMockContext('3.5.3');
      const result = phase.detectVersionUpgrade(context);
      expect(result).toBe(false);
    });

    it('should return true when versions differ', () => {
      // Create existing config with older version
      const configPath = join(testDir, '.agentic-qe', 'config.yaml');
      writeFileSync(configPath, 'version: "3.5.0"\n', 'utf-8');

      const context = createMockContext('3.5.3');
      const result = phase.detectVersionUpgrade(context);
      expect(result).toBe(true);
    });

    it('should handle version without quotes', () => {
      const configPath = join(testDir, '.agentic-qe', 'config.yaml');
      writeFileSync(configPath, 'version: 3.5.0\n', 'utf-8');

      const context = createMockContext('3.5.3');
      const result = phase.detectVersionUpgrade(context);
      expect(result).toBe(true);
    });

    it('should handle complex config files', () => {
      const configPath = join(testDir, '.agentic-qe', 'config.yaml');
      const complexConfig = `# Agentic QE v3 Configuration
# Generated by aqe init

version: "3.5.0"

project:
  name: "my-project"
  root: "/path/to/project"
  type: "single"

learning:
  enabled: true
`;
      writeFileSync(configPath, complexConfig, 'utf-8');

      const context = createMockContext('3.5.3');
      const result = phase.detectVersionUpgrade(context);
      expect(result).toBe(true);
    });

    it('should return false on read error', () => {
      // Create a directory instead of a file to cause a read error
      const configPath = join(testDir, '.agentic-qe', 'config.yaml');
      mkdirSync(configPath, { recursive: true });

      const context = createMockContext('3.5.3');
      const result = phase.detectVersionUpgrade(context);
      expect(result).toBe(false);
    });
  });

  describe('shouldOverwrite logic', () => {
    it('should NOT overwrite by default', () => {
      const context = createMockContext('3.5.3');
      const config = context.config as AQEInitConfig;

      const shouldOverwrite = context.options.upgrade || config.skills.overwrite;
      expect(shouldOverwrite).toBe(false);
    });

    it('should overwrite when upgrade flag is set', () => {
      const context = createMockContext('3.5.3', { upgrade: true });
      const config = context.config as AQEInitConfig;

      const shouldOverwrite = context.options.upgrade || config.skills.overwrite;
      expect(shouldOverwrite).toBe(true);
    });

    it('should overwrite when config.skills.overwrite is true', () => {
      const context = createMockContext('3.5.3');
      (context.config as AQEInitConfig).skills.overwrite = true;
      const config = context.config as AQEInitConfig;

      const shouldOverwrite = context.options.upgrade || config.skills.overwrite;
      expect(shouldOverwrite).toBe(true);
    });

    it('should overwrite in auto mode when version differs', () => {
      // Create existing config with older version
      const configPath = join(testDir, '.agentic-qe', 'config.yaml');
      writeFileSync(configPath, 'version: "3.5.0"\n', 'utf-8');

      const context = createMockContext('3.5.3', { autoMode: true });
      const config = context.config as AQEInitConfig;
      const isVersionUpgrade = phase.detectVersionUpgrade(context);

      const shouldOverwrite = context.options.upgrade || config.skills.overwrite ||
        (context.options.autoMode && isVersionUpgrade);

      expect(isVersionUpgrade).toBe(true);
      expect(shouldOverwrite).toBe(true);
    });

    it('should NOT overwrite in auto mode when version matches', () => {
      // Create existing config with same version
      const configPath = join(testDir, '.agentic-qe', 'config.yaml');
      writeFileSync(configPath, 'version: "3.5.3"\n', 'utf-8');

      const context = createMockContext('3.5.3', { autoMode: true });
      const config = context.config as AQEInitConfig;
      const isVersionUpgrade = phase.detectVersionUpgrade(context);

      const shouldOverwrite = context.options.upgrade || config.skills.overwrite ||
        (context.options.autoMode && isVersionUpgrade);

      expect(isVersionUpgrade).toBe(false);
      expect(shouldOverwrite).toBe(false);
    });
  });
});
