/**
 * Unit tests for add function
 * Generated by: qe-test-generator
 * Framework: Jest
 * Test Type: Unit test with boundary analysis
 */

import { add } from '../../../src/utils/math';

describe('add', () => {
  describe('basic functionality', () => {
    it('should add two positive numbers', () => {
      expect(add(2, 3)).toBe(5);
    });

    it('should add two negative numbers', () => {
      expect(add(-2, -3)).toBe(-5);
    });

    it('should add a positive and negative number', () => {
      expect(add(5, -3)).toBe(2);
    });

    it('should handle zero as first operand', () => {
      expect(add(0, 5)).toBe(5);
    });

    it('should handle zero as second operand', () => {
      expect(add(5, 0)).toBe(5);
    });

    it('should handle both operands as zero', () => {
      expect(add(0, 0)).toBe(0);
    });
  });

  describe('boundary cases', () => {
    it('should handle very large numbers', () => {
      expect(add(Number.MAX_SAFE_INTEGER - 1, 1)).toBe(Number.MAX_SAFE_INTEGER);
    });

    it('should handle very small numbers', () => {
      expect(add(Number.MIN_SAFE_INTEGER + 1, -1)).toBe(Number.MIN_SAFE_INTEGER);
    });

    it('should handle decimal numbers', () => {
      expect(add(0.1, 0.2)).toBeCloseTo(0.3, 10);
    });

    it('should handle negative decimal numbers', () => {
      expect(add(-0.5, -0.3)).toBeCloseTo(-0.8, 10);
    });
  });

  describe('edge cases', () => {
    it('should handle infinity', () => {
      expect(add(Infinity, 5)).toBe(Infinity);
      expect(add(-Infinity, 5)).toBe(-Infinity);
    });

    it('should handle NaN', () => {
      expect(add(NaN, 5)).toBe(NaN);
    });
  });
});
