import { Page, Locator, expect } from '@playwright/test';

/**
 * Base Page Object Model
 * Provides common functionality for all page objects
 *
 * Generated by: qe-queen-coordinator
 * Pattern: Page Object Model with Shopify theme selectors
 */
export class BasePage {
  readonly page: Page;

  // Common Shopify theme selectors
  readonly header: Locator;
  readonly footer: Locator;
  readonly cartIcon: Locator;
  readonly cartCount: Locator;
  readonly searchLink: Locator;
  readonly loginLink: Locator;
  readonly logo: Locator;
  readonly navigationMenu: Locator;

  constructor(page: Page) {
    this.page = page;

    // Header elements - Shopify Sauce theme selectors
    this.header = page.locator('header, #header, .site-header');
    this.footer = page.locator('footer, #footer, .site-footer');
    this.cartIcon = page.locator('[href="/cart"], .cart-link, #cart-icon');
    this.cartCount = page.locator('.cart-count, .cart-item-count, [data-cart-count]');
    this.searchLink = page.locator('[href="/search"], .search-link, [data-search]');
    this.loginLink = page.locator('[href="/account/login"], .account-link');
    this.logo = page.locator('.site-logo, .header-logo, [data-logo]');
    this.navigationMenu = page.locator('nav, .main-nav, .site-nav');
  }

  /**
   * Navigate to a specific path
   */
  async goto(path: string = '/') {
    await this.page.goto(path, { waitUntil: 'domcontentloaded' });
  }

  /**
   * Wait for page to be fully loaded
   */
  async waitForPageLoad() {
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Get current URL
   */
  async getCurrentUrl(): Promise<string> {
    return this.page.url();
  }

  /**
   * Get page title
   */
  async getPageTitle(): Promise<string> {
    return this.page.title();
  }

  /**
   * Navigate to cart
   */
  async goToCart() {
    await this.cartIcon.click();
    await this.page.waitForURL('**/cart');
  }

  /**
   * Navigate to login page
   */
  async goToLogin() {
    await this.loginLink.click();
    await this.page.waitForURL('**/account/login');
  }

  /**
   * Get cart item count from header
   */
  async getCartItemCount(): Promise<number> {
    const countText = await this.cartCount.textContent();
    if (!countText) return 0;
    const match = countText.match(/\d+/);
    return match ? parseInt(match[0], 10) : 0;
  }

  /**
   * Take a screenshot with descriptive name
   */
  async takeScreenshot(name: string) {
    await this.page.screenshot({
      path: `test-results/screenshots/${name}.png`,
      fullPage: true
    });
  }

  /**
   * Wait for element to be visible
   */
  async waitForElement(selector: string, timeout: number = 10000) {
    await this.page.locator(selector).waitFor({
      state: 'visible',
      timeout
    });
  }

  /**
   * Check if element exists on page
   */
  async elementExists(selector: string): Promise<boolean> {
    const count = await this.page.locator(selector).count();
    return count > 0;
  }

  /**
   * Scroll to bottom of page
   */
  async scrollToBottom() {
    await this.page.evaluate(() => {
      window.scrollTo(0, document.body.scrollHeight);
    });
  }

  /**
   * Accept cookies if banner present
   */
  async acceptCookiesIfPresent() {
    const cookieBanner = this.page.locator('[data-cookie-banner], .cookie-banner, #cookie-consent');
    if (await cookieBanner.isVisible({ timeout: 2000 }).catch(() => false)) {
      const acceptButton = cookieBanner.locator('button, [data-accept]').first();
      if (await acceptButton.isVisible()) {
        await acceptButton.click();
      }
    }
  }

  /**
   * Verify page loaded without errors
   */
  async verifyNoErrors() {
    const errors: string[] = [];

    this.page.on('pageerror', (error) => {
      errors.push(error.message);
    });

    await this.page.waitForLoadState('load');

    if (errors.length > 0) {
      console.warn('Page errors detected:', errors);
    }

    return errors;
  }
}
