import { Page, Locator, expect } from '@playwright/test';
import { BasePage } from './BasePage';

/**
 * Login Page Object Model
 * Handles authentication interactions
 *
 * Generated by: qe-queen-coordinator
 */
export class LoginPage extends BasePage {
  // Login form
  readonly emailInput: Locator;
  readonly passwordInput: Locator;
  readonly loginButton: Locator;
  readonly loginForm: Locator;

  // Password recovery
  readonly forgotPasswordLink: Locator;
  readonly recoveryEmailInput: Locator;
  readonly recoverButton: Locator;
  readonly recoveryForm: Locator;
  readonly recoverySuccessMessage: Locator;

  // Registration link
  readonly createAccountLink: Locator;

  // Error messages
  readonly errorMessage: Locator;
  readonly invalidCredentialsError: Locator;

  // hCaptcha
  readonly captchaContainer: Locator;

  constructor(page: Page) {
    super(page);

    // Login form selectors
    this.emailInput = page.locator('#customer_email, [name="customer[email]"], input[type="email"]');
    this.passwordInput = page.locator('#customer_password, [name="customer[password]"], input[type="password"]');
    this.loginButton = page.locator('button[type="submit"]:has-text("Sign In"), input[type="submit"]');
    this.loginForm = page.locator('#customer_login, form[action*="/account/login"]');

    // Password recovery
    this.forgotPasswordLink = page.locator('a:has-text("Forgot"), [data-recover]');
    this.recoveryEmailInput = page.locator('#recover_email, [name="email"]');
    this.recoverButton = page.locator('button:has-text("Reset"), [data-recover-submit]');
    this.recoveryForm = page.locator('#recover_password, form[action*="recover"]');
    this.recoverySuccessMessage = page.locator('.recover-success, :text("email to reset")');

    // Create account
    this.createAccountLink = page.locator('a:has-text("Create account"), a:has-text("Sign up"), a[href*="/account/register"]');

    // Errors
    this.errorMessage = page.locator('.errors, .error-message, [data-error]');
    this.invalidCredentialsError = page.locator(':text("Incorrect"), :text("Invalid")');

    // Captcha
    this.captchaContainer = page.locator('.h-captcha, [data-hcaptcha]');
  }

  /**
   * Navigate to login page
   */
  async navigate() {
    await this.goto('/account/login');
    await this.waitForPageLoad();
  }

  /**
   * Login with credentials
   */
  async login(email: string, password: string) {
    await this.emailInput.fill(email);
    await this.passwordInput.fill(password);
    await this.loginButton.click();
    // Wait for navigation or error
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Check if login was successful
   */
  async isLoginSuccessful(): Promise<boolean> {
    // Successful login redirects to account page
    const url = this.page.url();
    return url.includes('/account') && !url.includes('/login');
  }

  /**
   * Check if login failed
   */
  async hasLoginError(): Promise<boolean> {
    return await this.errorMessage.isVisible().catch(() => false) ||
           await this.invalidCredentialsError.isVisible().catch(() => false);
  }

  /**
   * Get error message text
   */
  async getErrorMessage(): Promise<string> {
    if (await this.errorMessage.isVisible()) {
      return await this.errorMessage.textContent() || '';
    }
    return '';
  }

  /**
   * Click forgot password link
   */
  async clickForgotPassword() {
    await this.forgotPasswordLink.click();
    await this.page.waitForTimeout(500); // Wait for form toggle
  }

  /**
   * Submit password recovery
   */
  async submitPasswordRecovery(email: string) {
    await this.clickForgotPassword();
    await this.recoveryEmailInput.fill(email);
    await this.recoverButton.click();
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Check if recovery success message shown
   */
  async isRecoverySuccessful(): Promise<boolean> {
    return await this.recoverySuccessMessage.isVisible().catch(() => false);
  }

  /**
   * Navigate to registration page
   */
  async goToRegistration() {
    await this.createAccountLink.click();
    await this.page.waitForURL('**/account/register');
  }

  /**
   * Verify login page loaded
   */
  async verifyLoginPageLoaded() {
    await expect(this.page).toHaveURL(/.*\/account\/login.*/);
    await expect(this.loginForm.or(this.emailInput)).toBeVisible();
  }

  /**
   * Check if captcha is present
   */
  async hasCaptcha(): Promise<boolean> {
    return await this.captchaContainer.isVisible().catch(() => false);
  }

  /**
   * Test login with invalid credentials
   */
  async attemptInvalidLogin() {
    await this.login('invalid@test.com', 'wrongpassword123');
    return await this.hasLoginError();
  }
}
