import { Page, Locator, expect } from '@playwright/test';
import { BasePage } from './BasePage';

/**
 * Registration Page Object Model
 * Handles account creation interactions
 *
 * Generated by: qe-queen-coordinator
 */
export class RegisterPage extends BasePage {
  // Registration form
  readonly registrationForm: Locator;
  readonly firstNameInput: Locator;
  readonly lastNameInput: Locator;
  readonly emailInput: Locator;
  readonly passwordInput: Locator;
  readonly createAccountButton: Locator;

  // Login link
  readonly loginLink: Locator;

  // Error messages
  readonly errorMessages: Locator;
  readonly emailTakenError: Locator;
  readonly passwordError: Locator;

  // Success state
  readonly successMessage: Locator;

  // hCaptcha
  readonly captchaContainer: Locator;

  constructor(page: Page) {
    super(page);

    // Form selectors
    this.registrationForm = page.locator('#create_customer, form[action*="/account"]');
    this.firstNameInput = page.locator('#first_name, [name="customer[first_name]"]');
    this.lastNameInput = page.locator('#last_name, [name="customer[last_name]"]');
    this.emailInput = page.locator('#email, [name="customer[email]"], input[type="email"]');
    this.passwordInput = page.locator('#password, [name="customer[password]"], input[type="password"]');
    this.createAccountButton = page.locator('button[type="submit"]:has-text("Create"), input[value*="Create"]');

    // Login link
    this.loginLink = page.locator('a:has-text("Sign in"), a:has-text("Log in"), a[href*="/account/login"]');

    // Errors
    this.errorMessages = page.locator('.errors, .error-message, ul.errors li');
    this.emailTakenError = page.locator(':text("already taken"), :text("already exists")');
    this.passwordError = page.locator(':text("password"), :text("Password")');

    // Success
    this.successMessage = page.locator('.success-message, :text("Welcome")');

    // Captcha
    this.captchaContainer = page.locator('.h-captcha, [data-hcaptcha]');
  }

  /**
   * Navigate to registration page
   */
  async navigate() {
    await this.goto('/account/register');
    await this.waitForPageLoad();
  }

  /**
   * Fill registration form
   */
  async fillRegistrationForm(userData: {
    firstName: string;
    lastName: string;
    email: string;
    password: string;
  }) {
    if (await this.firstNameInput.isVisible()) {
      await this.firstNameInput.fill(userData.firstName);
    }
    if (await this.lastNameInput.isVisible()) {
      await this.lastNameInput.fill(userData.lastName);
    }
    await this.emailInput.fill(userData.email);
    await this.passwordInput.fill(userData.password);
  }

  /**
   * Submit registration form
   */
  async submitRegistration() {
    await this.createAccountButton.click();
    await this.page.waitForLoadState('networkidle');
  }

  /**
   * Complete registration process
   */
  async register(userData: {
    firstName: string;
    lastName: string;
    email: string;
    password: string;
  }) {
    await this.fillRegistrationForm(userData);
    await this.submitRegistration();
  }

  /**
   * Check if registration was successful
   */
  async isRegistrationSuccessful(): Promise<boolean> {
    const url = this.page.url();
    // Successful registration typically redirects to account page
    return url.includes('/account') && !url.includes('/register');
  }

  /**
   * Check if registration has errors
   */
  async hasRegistrationError(): Promise<boolean> {
    return await this.errorMessages.isVisible().catch(() => false);
  }

  /**
   * Check if email already taken error
   */
  async isEmailTaken(): Promise<boolean> {
    return await this.emailTakenError.isVisible().catch(() => false);
  }

  /**
   * Get all error messages
   */
  async getErrorMessages(): Promise<string[]> {
    const errors = await this.errorMessages.allTextContents();
    return errors.map(e => e.trim()).filter(e => e.length > 0);
  }

  /**
   * Navigate to login page
   */
  async goToLogin() {
    await this.loginLink.click();
    await this.page.waitForURL('**/account/login');
  }

  /**
   * Verify registration page loaded
   */
  async verifyRegistrationPageLoaded() {
    await expect(this.page).toHaveURL(/.*\/account\/register.*/);
    await expect(this.registrationForm.or(this.emailInput)).toBeVisible();
  }

  /**
   * Check if captcha is present
   */
  async hasCaptcha(): Promise<boolean> {
    return await this.captchaContainer.isVisible().catch(() => false);
  }

  /**
   * Generate unique test email
   */
  generateTestEmail(): string {
    const timestamp = Date.now();
    return `test_user_${timestamp}@example.com`;
  }

  /**
   * Attempt registration with invalid data
   */
  async attemptInvalidRegistration(invalidField: 'email' | 'password') {
    const invalidData = {
      firstName: 'Test',
      lastName: 'User',
      email: invalidField === 'email' ? 'invalid-email' : 'valid@test.com',
      password: invalidField === 'password' ? '123' : 'ValidPassword123!'
    };

    await this.register(invalidData);
    return await this.hasRegistrationError();
  }
}
