/**
 * Phase 10: Workers
 * Configures background workers for continuous monitoring
 */

import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';

import {
  BasePhase,
  type InitContext,
} from './phase-interface.js';
import type { AQEInitConfig } from '../types.js';

interface WorkerRegistration {
  name: string;
  enabled: boolean;
  interval: number;
  lastRun: string | null;
  status: 'pending' | 'running' | 'completed' | 'error';
}

export interface WorkersResult {
  workersDir: string;
  workersConfigured: number;
  registryPath: string;
}

/**
 * Workers phase - configures background workers
 */
export class WorkersPhase extends BasePhase<WorkersResult> {
  readonly name = 'workers';
  readonly description = 'Configure background workers';
  readonly order = 100;
  readonly critical = false;
  readonly requiresPhases = ['configuration'] as const;

  async shouldRun(context: InitContext): Promise<boolean> {
    const config = context.config as AQEInitConfig;
    return config?.workers?.daemonAutoStart && (config?.workers?.enabled?.length ?? 0) > 0;
  }

  protected async run(context: InitContext): Promise<WorkersResult> {
    const config = context.config as AQEInitConfig;
    const { projectRoot } = context;

    if (!config.workers.daemonAutoStart || config.workers.enabled.length === 0) {
      return {
        workersDir: '',
        workersConfigured: 0,
        registryPath: '',
      };
    }

    // Create workers directory
    const workersDir = join(projectRoot, '.agentic-qe', 'workers');
    if (!existsSync(workersDir)) {
      mkdirSync(workersDir, { recursive: true });
    }

    // Default intervals
    const defaultIntervals: Record<string, number> = {
      'pattern-consolidator': 60000,
      'coverage-gap-scanner': 300000,
      'flaky-test-detector': 600000,
      'routing-accuracy-monitor': 120000,
    };

    // Build worker registry
    const workerRegistry: Record<string, WorkerRegistration> = {};

    for (const workerName of config.workers.enabled) {
      workerRegistry[workerName] = {
        name: workerName,
        enabled: true,
        interval: config.workers.intervals[workerName] || defaultIntervals[workerName] || 60000,
        lastRun: null,
        status: 'pending',
      };
    }

    // Write registry
    const registryPath = join(workersDir, 'registry.json');
    const registryData = {
      version: config.version,
      maxConcurrent: config.workers.maxConcurrent,
      workers: workerRegistry,
      createdAt: new Date().toISOString(),
      daemonPid: null,
    };
    writeFileSync(registryPath, JSON.stringify(registryData, null, 2), 'utf-8');

    // Write individual worker configs
    for (const workerName of config.workers.enabled) {
      const workerConfigPath = join(workersDir, `${workerName}.json`);
      const workerConfig = {
        name: workerName,
        enabled: true,
        interval: config.workers.intervals[workerName] || defaultIntervals[workerName] || 60000,
        projectRoot,
        dataDir: join(projectRoot, '.agentic-qe', 'data'),
        createdAt: new Date().toISOString(),
      };
      writeFileSync(workerConfigPath, JSON.stringify(workerConfig, null, 2), 'utf-8');
    }

    // Write daemon startup script
    const daemonScriptPath = join(workersDir, 'start-daemon.sh');
    const daemonScript = `#!/bin/bash
# AQE v3 Worker Daemon Startup Script
# Generated by aqe init

PROJECT_ROOT="${projectRoot}"
WORKERS_DIR="$PROJECT_ROOT/.agentic-qe/workers"
PID_FILE="$WORKERS_DIR/daemon.pid"

# Check if already running
if [ -f "$PID_FILE" ]; then
  PID=$(cat "$PID_FILE")
  if kill -0 "$PID" 2>/dev/null; then
    echo "Daemon already running (PID: $PID)"
    exit 0
  fi
fi

# AQE v3 hooks work via CLI commands
echo "AQE v3 hooks work via CLI commands"
echo "Use: npx aqe hooks session-start"
`;
    writeFileSync(daemonScriptPath, daemonScript, { mode: 0o755 });

    context.services.log(`  Workers dir: ${workersDir}`);
    context.services.log(`  Workers: ${config.workers.enabled.join(', ')}`);

    return {
      workersDir,
      workersConfigured: config.workers.enabled.length,
      registryPath,
    };
  }
}

// Instance exported from index.ts
