/**
 * Phase 12: Verification
 * Verifies the installation and writes version marker
 */

import { existsSync } from 'fs';
import { join, dirname } from 'path';
import { mkdirSync, writeFileSync } from 'fs';
import { createRequire } from 'module';

import {
  BasePhase,
  type InitContext,
} from './phase-interface.js';
import type { AQEInitConfig } from '../types.js';

const require = createRequire(import.meta.url);

export interface VerificationResult {
  verified: boolean;
  versionWritten: boolean;
  configSaved: boolean;
  checks: {
    name: string;
    passed: boolean;
  }[];
}

/**
 * Verification phase - verifies installation and writes markers
 */
export class VerificationPhase extends BasePhase<VerificationResult> {
  readonly name = 'verification';
  readonly description = 'Verify installation';
  readonly order = 120;
  readonly critical = true;
  readonly requiresPhases = ['database', 'configuration'] as const;

  protected async run(context: InitContext): Promise<VerificationResult> {
    const config = context.config as AQEInitConfig;
    const { projectRoot } = context;

    const checks: { name: string; passed: boolean }[] = [];

    // Check database exists
    const dbPath = join(projectRoot, '.agentic-qe', 'memory.db');
    checks.push({
      name: 'Database exists',
      passed: existsSync(dbPath),
    });

    // Check .agentic-qe directory
    checks.push({
      name: '.agentic-qe directory',
      passed: existsSync(join(projectRoot, '.agentic-qe')),
    });

    // Check config (will be written below)
    const configPath = join(projectRoot, '.agentic-qe', 'config.yaml');

    // Save configuration
    await this.saveConfig(config, projectRoot);
    checks.push({
      name: 'Config saved',
      passed: existsSync(configPath),
    });

    // Write version marker
    const versionWritten = await this.writeVersionToDb(config.version, projectRoot);
    checks.push({
      name: 'Version marker',
      passed: versionWritten,
    });

    // All critical checks must pass
    const criticalChecks = ['Database exists', '.agentic-qe directory', 'Config saved'];
    const allCriticalPassed = checks
      .filter(c => criticalChecks.includes(c.name))
      .every(c => c.passed);

    context.services.log('  Verification checks:');
    for (const check of checks) {
      context.services.log(`    ${check.passed ? '✓' : '✗'} ${check.name}`);
    }

    return {
      verified: allCriticalPassed,
      versionWritten,
      configSaved: existsSync(configPath),
      checks,
    };
  }

  /**
   * Write AQE version to memory.db
   */
  private async writeVersionToDb(version: string, projectRoot: string): Promise<boolean> {
    const memoryDbPath = join(projectRoot, '.agentic-qe', 'memory.db');

    try {
      const dir = dirname(memoryDbPath);
      if (!existsSync(dir)) {
        mkdirSync(dir, { recursive: true });
      }

      const Database = require('better-sqlite3');
      const db = new Database(memoryDbPath);

      try {
        db.exec(`
          CREATE TABLE IF NOT EXISTS kv_store (
            key TEXT NOT NULL,
            namespace TEXT NOT NULL,
            value TEXT NOT NULL,
            expires_at INTEGER,
            created_at INTEGER DEFAULT (strftime('%s', 'now') * 1000),
            PRIMARY KEY (namespace, key)
          );
        `);

        const now = Date.now();
        db.prepare(`
          INSERT OR REPLACE INTO kv_store (key, namespace, value, created_at)
          VALUES (?, '_system', ?, ?)
        `).run('aqe_version', JSON.stringify(version), now);

        db.prepare(`
          INSERT OR REPLACE INTO kv_store (key, namespace, value, created_at)
          VALUES (?, '_system', ?, ?)
        `).run('init_timestamp', JSON.stringify(new Date().toISOString()), now);

        db.close();
        return true;
      } catch (err) {
        db.close();
        return false;
      }
    } catch {
      return false;
    }
  }

  /**
   * Save configuration to YAML file
   */
  private async saveConfig(config: AQEInitConfig, projectRoot: string): Promise<void> {
    const configDir = join(projectRoot, '.agentic-qe');
    if (!existsSync(configDir)) {
      mkdirSync(configDir, { recursive: true });
    }

    const yaml = this.configToYAML(config);
    const configPath = join(configDir, 'config.yaml');
    writeFileSync(configPath, yaml, 'utf-8');
  }

  /**
   * Convert config to YAML
   */
  private configToYAML(config: AQEInitConfig): string {
    const lines: string[] = [
      '# Agentic QE v3 Configuration',
      '# Generated by aqe init',
      `# ${new Date().toISOString()}`,
      '',
      `version: "${config.version}"`,
      '',
      'project:',
      `  name: "${config.project.name}"`,
      `  root: "${config.project.root}"`,
      `  type: "${config.project.type}"`,
      '',
      'learning:',
      `  enabled: ${config.learning.enabled}`,
      `  embeddingModel: "${config.learning.embeddingModel}"`,
      '  hnswConfig:',
      `    M: ${config.learning.hnswConfig.M}`,
      `    efConstruction: ${config.learning.hnswConfig.efConstruction}`,
      `    efSearch: ${config.learning.hnswConfig.efSearch}`,
      `  qualityThreshold: ${config.learning.qualityThreshold}`,
      `  promotionThreshold: ${config.learning.promotionThreshold}`,
      `  pretrainedPatterns: ${config.learning.pretrainedPatterns}`,
      '',
      'routing:',
      `  mode: "${config.routing.mode}"`,
      `  confidenceThreshold: ${config.routing.confidenceThreshold}`,
      `  feedbackEnabled: ${config.routing.feedbackEnabled}`,
      '',
      'workers:',
      '  enabled:',
      ...config.workers.enabled.map(w => `    - "${w}"`),
      '  intervals:',
      ...Object.entries(config.workers.intervals).map(([k, v]) => `    ${k}: ${v}`),
      `  maxConcurrent: ${config.workers.maxConcurrent}`,
      `  daemonAutoStart: ${config.workers.daemonAutoStart}`,
      '',
      'hooks:',
      `  claudeCode: ${config.hooks.claudeCode}`,
      `  preCommit: ${config.hooks.preCommit}`,
      `  ciIntegration: ${config.hooks.ciIntegration}`,
      '',
      'skills:',
      `  install: ${config.skills.install}`,
      `  installV2: ${config.skills.installV2}`,
      `  installV3: ${config.skills.installV3}`,
      `  overwrite: ${config.skills.overwrite}`,
      '',
      'domains:',
      '  enabled:',
      ...config.domains.enabled.map(d => `    - "${d}"`),
      '  disabled:',
      ...config.domains.disabled.map(d => `    - "${d}"`),
      '',
      'agents:',
      `  maxConcurrent: ${config.agents.maxConcurrent}`,
      `  defaultTimeout: ${config.agents.defaultTimeout}`,
      '',
    ];

    return lines.join('\n');
  }
}

// Instance exported from index.ts
