/**
 * Page Object Model exports
 * Centralized export for all page objects
 *
 * Generated by: qe-queen-coordinator
 */

export { BasePage } from './BasePage';
export { HomePage } from './HomePage';
export { CatalogPage } from './CatalogPage';
export { ProductPage } from './ProductPage';
export { CartPage } from './CartPage';
export { CheckoutPage } from './CheckoutPage';
export { LoginPage } from './LoginPage';
export { RegisterPage } from './RegisterPage';
export { SearchPage } from './SearchPage';
