import { Page, Locator, expect } from '@playwright/test';

/**
 * Base Page Object for Sauce Demo Shopify Store
 * Provides common functionality for all page objects
 *
 * QE Assessment: sauce-demo.myshopify.com
 * Generated by: QE Queen Coordinator - qe-test-architect domain
 */
export abstract class BasePage {
  readonly page: Page;

  // Common header elements (Shopify theme: Simple OLD)
  readonly header: Locator;
  readonly logo: Locator;
  readonly searchIcon: Locator;
  readonly searchInput: Locator;
  readonly cartIcon: Locator;
  readonly cartCount: Locator;
  readonly accountLink: Locator;

  // Navigation elements
  readonly mainNav: Locator;
  readonly homeLink: Locator;
  readonly catalogLink: Locator;
  readonly blogLink: Locator;
  readonly aboutLink: Locator;

  // Footer elements
  readonly footer: Locator;
  readonly footerNav: Locator;

  // Common Shopify elements
  readonly announcementBar: Locator;
  readonly cookieBanner: Locator;

  constructor(page: Page) {
    this.page = page;

    // Header selectors for Shopify Simple theme
    this.header = page.locator('header, .site-header, #shopify-section-header');
    this.logo = page.locator('.site-header__logo, .header__logo, [class*="logo"]').first();
    this.searchIcon = page.locator('[data-search], .site-header__search, [aria-label*="Search"]');
    this.searchInput = page.locator('input[type="search"], input[name="q"], .search-bar__input');
    this.cartIcon = page.locator('[href="/cart"], .site-header__cart, .cart-link');
    this.cartCount = page.locator('.cart-count, .cart-link__bubble, [data-cart-count]');
    this.accountLink = page.locator('[href="/account"], .site-header__account');

    // Navigation selectors
    this.mainNav = page.locator('nav, .site-nav, .main-menu');
    this.homeLink = page.locator('nav a[href="/"], .site-nav a[href="/"]').first();
    this.catalogLink = page.locator('a[href*="/collections"], a:has-text("Catalog")').first();
    this.blogLink = page.locator('a[href*="/blogs"], a:has-text("Blog")').first();
    this.aboutLink = page.locator('a[href*="/about"], a:has-text("About")').first();

    // Footer selectors
    this.footer = page.locator('footer, .site-footer, #shopify-section-footer');
    this.footerNav = page.locator('footer nav, .footer-nav');

    // Shopify-specific elements
    this.announcementBar = page.locator('.announcement-bar, #shopify-section-announcement-bar');
    this.cookieBanner = page.locator('[data-cookie-banner], .cookie-banner, #cookie-consent');
  }

  /**
   * Navigate to page and wait for network idle
   */
  async goto(path: string = ''): Promise<void> {
    await this.page.goto(path, { waitUntil: 'networkidle' });
    await this.dismissPopupsIfPresent();
  }

  /**
   * Dismiss any popups/modals that may interfere with tests
   */
  async dismissPopupsIfPresent(): Promise<void> {
    // Handle cookie consent
    const cookieAccept = this.page.locator('[data-cookie-accept], .cookie-accept, button:has-text("Accept")');
    if (await cookieAccept.isVisible({ timeout: 2000 }).catch(() => false)) {
      await cookieAccept.click();
    }

    // Handle newsletter popup
    const popupClose = this.page.locator('.popup-close, [data-modal-close], .modal__close');
    if (await popupClose.isVisible({ timeout: 1000 }).catch(() => false)) {
      await popupClose.click();
    }
  }

  /**
   * Get current cart count
   */
  async getCartCount(): Promise<number> {
    const countText = await this.cartCount.textContent().catch(() => '0');
    const match = countText?.match(/\d+/);
    return match ? parseInt(match[0], 10) : 0;
  }

  /**
   * Open the cart
   */
  async openCart(): Promise<void> {
    await this.cartIcon.click();
    await this.page.waitForURL('**/cart');
  }

  /**
   * Search for a product
   */
  async search(query: string): Promise<void> {
    await this.searchIcon.click();
    await this.searchInput.fill(query);
    await this.searchInput.press('Enter');
    await this.page.waitForURL('**/search*');
  }

  /**
   * Navigate to catalog/collection
   */
  async goToCatalog(): Promise<void> {
    await this.catalogLink.click();
    await this.page.waitForURL('**/collections/**');
  }

  /**
   * Wait for Shopify page to fully load
   */
  async waitForShopifyReady(): Promise<void> {
    // Wait for Shopify's analytics to load (indicates page is ready)
    await this.page.waitForFunction(() => {
      return (window as any).Shopify?.analytics || document.readyState === 'complete';
    }, { timeout: 10000 }).catch(() => {
      // Fallback: just ensure DOM is loaded
    });
  }

  /**
   * Take screenshot with descriptive name
   */
  async takeScreenshot(name: string): Promise<void> {
    await this.page.screenshot({
      path: `./reports/screenshots/${name}-${Date.now()}.png`,
      fullPage: true
    });
  }

  /**
   * Assert page loaded successfully
   */
  async assertPageLoaded(): Promise<void> {
    await expect(this.header).toBeVisible();
    await expect(this.page).not.toHaveTitle(/error|404|not found/i);
  }
}
