/**
 * Condensed CLAUDE.md template for aqe init
 * ONLY includes AQE-specific instructions
 * NO project-specific or Claude Flow instructions
 */

export function generateCondensedClaudeMd(config: {
  agentCount: number;
  skillCount?: number;
  topology?: string;
  maxAgents?: number;
  testingFocus?: string[];
  environments?: string[];
  frameworks?: string[];
  routing?: any;
  streaming?: any;
}, packageVersion: string): string {
  const skills = config.skillCount || 41;
  return `# Agentic QE Fleet Configuration

## ⚠️ INTEGRITY RULE (ABSOLUTE)

**We value the quality we deliver to our users.**

- ❌ NO shortcuts - do the work properly or don't do it
- ❌ NO fake data - use real data, real tests, real results
- ❌ NO false claims - only report what actually works and is verified
- ✅ ALWAYS implement all code/tests with proper implementation
- ✅ ALWAYS verify before claiming success
- ✅ ALWAYS use real database queries, not mocks, for integration tests
- ✅ ALWAYS run actual tests, not assume they pass

---

## 🤖 Agentic QE Fleet Quick Reference

**${config.agentCount} QE Agents:** Test generation, coverage analysis, performance, security, flaky detection
**${skills} QE Skills:** agentic-quality-engineering, tdd-london-chicago, api-testing-patterns, six-thinking-hats, brutal-honesty-review, cicd-pipeline-qe-orchestrator
**8 Slash Commands:** \`/aqe-execute\`, \`/aqe-generate\`, \`/aqe-coverage\`, \`/aqe-quality\`

### 📚 Complete Documentation

- **[Agent Reference](https://github.com/proffesor-for-testing/agentic-qe/blob/main/docs/reference/agents.md)** - All ${config.agentCount} QE agents with capabilities and usage
- **[Skills Reference](https://github.com/proffesor-for-testing/agentic-qe/blob/main/docs/reference/skills.md)** - All ${skills} QE skills organized by category
- **[Usage Guide](https://github.com/proffesor-for-testing/agentic-qe/blob/main/docs/reference/usage.md)** - Complete usage examples and workflows

### 🎯 Quick Start

**Spawn agents:**
\`\`\`javascript
Task("Generate tests", "Create test suite for UserService", "qe-test-generator")
Task("Analyze coverage", "Find gaps using O(log n)", "qe-coverage-analyzer")
\`\`\`

**Check learning status:**
\`\`\`bash
aqe learn status --agent test-gen
aqe patterns list --framework jest
\`\`\`

### 🎯 Fleet Configuration

**Topology**: ${config.topology || 'hierarchical'}
**Max Agents**: ${config.maxAgents || 10}
**Testing Focus**: ${config.testingFocus?.join(', ') || 'All areas'}
**Environments**: ${config.environments?.join(', ') || 'Not specified'}
**Frameworks**: ${config.frameworks?.join(', ') || 'jest'}

### 📋 Memory Namespace

Agents share state through the **\`aqe/*\` memory namespace**:
- \`aqe/test-plan/*\` - Test planning and requirements
- \`aqe/coverage/*\` - Coverage analysis and gaps
- \`aqe/quality/*\` - Quality metrics and gates
- \`aqe/performance/*\` - Performance test results
- \`aqe/security/*\` - Security scan findings
- \`aqe/swarm/coordination\` - Cross-agent coordination

### 💡 Key Principles
- Use Task tool for agent execution (not just MCP)
- Batch all operations in single messages (TodoWrite, file ops, etc.)
- Test with actual databases, not mocks
- Document only what actually works

---

**Generated by**: Agentic QE Fleet v${packageVersion}
**Initialization Date**: ${new Date().toISOString()}
**Fleet Topology**: ${config.topology || 'hierarchical'}
`;
}
