/**
 * Idempotent file writers for `aqe init` (#778).
 *
 * A repeat `aqe init` on an unchanged project must be a byte-stable
 * convergence step: files whose content would not change are left alone (no
 * rewrite, so the mtime is preserved too), and volatile fields such as
 * generation timestamps are carried over from the existing file unless
 * something else in that file actually changed.
 */

import { copyFileSync, existsSync, readFileSync, writeFileSync } from 'fs';

import { safeJsonParse } from '../shared/safe-json.js';

/**
 * Write `content` to `path` only when the bytes on disk differ.
 * @returns true when the file was written.
 */
export function writeFileIfChanged(path: string, content: string | Buffer): boolean {
  const next = typeof content === 'string' ? Buffer.from(content, 'utf-8') : content;
  try {
    if (existsSync(path) && readFileSync(path).equals(next)) return false;
  } catch {
    // Unreadable target — fall through and (re)write it.
  }
  if (typeof content === 'string') writeFileSync(path, content, 'utf-8');
  else writeFileSync(path, content);
  return true;
}

/**
 * Copy `src` to `dest` only when `dest` is missing or its bytes differ.
 * Uses copyFileSync for the actual copy so file-mode semantics are unchanged.
 * @returns true when the file was copied.
 */
export function copyFileIfChanged(src: string, dest: string): boolean {
  try {
    if (existsSync(dest) && readFileSync(dest).equals(readFileSync(src))) return false;
  } catch {
    // Unreadable target — fall through and copy.
  }
  copyFileSync(src, dest);
  return true;
}

/**
 * Write a text file whose content embeds a volatile line (e.g. a generation
 * timestamp). When the existing file matches `content` on every line except
 * the lines matching `volatileLine`, the file is left untouched.
 * @returns true when the file was written.
 */
export function writeTextIfChangedIgnoring(
  path: string,
  content: string,
  volatileLine: RegExp,
): boolean {
  try {
    if (existsSync(path)) {
      const strip = (text: string): string =>
        text.split('\n').filter((line) => !volatileLine.test(line)).join('\n');
      if (strip(readFileSync(path, 'utf-8')) === strip(content)) return false;
    }
  } catch {
    // Unreadable target — fall through and write.
  }
  writeFileSync(path, content, 'utf-8');
  return true;
}

/** The `*Generated by AQE v3 init on <ISO>*` footer of generated index docs. */
export const GENERATED_ON_LINE = /^\*Generated by AQE v3 init on [^*]+\*$/;

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/** JSON serialization with object keys sorted, for order-insensitive comparison. */
export function canonicalJson(value: unknown): string {
  return JSON.stringify(value, (_key, v: unknown) => {
    if (!isPlainObject(v)) return v;
    const sorted: Record<string, unknown> = {};
    for (const k of Object.keys(v).sort()) sorted[k] = v[k];
    return sorted;
  });
}

/** Deep structural equality of two JSON values, ignoring object key order. */
export function jsonEquivalent(a: unknown, b: unknown): boolean {
  return canonicalJson(a) === canonicalJson(b);
}

function getPath(obj: unknown, path: readonly string[]): unknown {
  let cur: unknown = obj;
  for (const key of path) {
    if (!isPlainObject(cur)) return undefined;
    cur = cur[key];
  }
  return cur;
}

function setPath(obj: Record<string, unknown>, path: readonly string[], value: unknown): void {
  let cur: Record<string, unknown> = obj;
  for (const key of path.slice(0, -1)) {
    if (!isPlainObject(cur[key])) return;
    cur = cur[key] as Record<string, unknown>;
  }
  const last = path[path.length - 1];
  if (last in cur) cur[last] = value;
}

/**
 * Carry volatile fields (timestamps) over from `previous` into `next` when
 * `next` is otherwise identical to `previous`.
 *
 * - Unchanged (apart from the volatile fields): `next` is mutated to hold the
 *   previous values and `false` is returned — the caller should not write.
 * - Changed, or no previous document: `next` keeps its fresh values and
 *   `true` is returned — the caller should write.
 */
export function stabilizeVolatileFields(
  previous: unknown,
  next: Record<string, unknown>,
  volatilePaths: ReadonlyArray<readonly string[]>,
): boolean {
  if (!isPlainObject(previous)) return true;
  const candidate = JSON.parse(JSON.stringify(next)) as Record<string, unknown>;
  for (const path of volatilePaths) {
    const prevValue = getPath(previous, path);
    if (prevValue !== undefined && getPath(candidate, path) !== undefined) {
      setPath(candidate, path, prevValue);
    }
  }
  if (!jsonEquivalent(previous, candidate)) return true;
  for (const path of volatilePaths) {
    const prevValue = getPath(previous, path);
    if (prevValue !== undefined && getPath(next, path) !== undefined) setPath(next, path, prevValue);
  }
  return false;
}

/** Read and parse a JSON file, or return undefined when missing/unparseable. */
export function readJsonIfPresent(path: string): unknown {
  if (!existsSync(path)) return undefined;
  try {
    return safeJsonParse<unknown>(readFileSync(path, 'utf-8'));
  } catch {
    return undefined;
  }
}

/**
 * Write a generated JSON document (2-space indent) unless it is equivalent to
 * the one already on disk, preserving the existing values of `volatilePaths`
 * (e.g. `[['createdAt']]`) when nothing else changed.
 * @returns true when the file was written.
 */
export function writeJsonIfChanged(
  path: string,
  doc: Record<string, unknown>,
  volatilePaths: ReadonlyArray<readonly string[]> = [],
): boolean {
  const previous = readJsonIfPresent(path);
  if (previous !== undefined && !stabilizeVolatileFields(previous, doc, volatilePaths)) {
    return false;
  }
  writeFileSync(path, JSON.stringify(doc, null, 2), 'utf-8');
  return true;
}
