/**
 * Test Data Fixtures for Sauce Demo E2E Tests
 *
 * QE Assessment: sauce-demo.myshopify.com
 * Generated by: QE Queen Coordinator - qe-test-architect domain
 */

export const TestData = {
  // Product data based on site analysis
  products: {
    greyJacket: {
      name: 'Grey jacket',
      handle: 'grey-jacket',
      price: '55.00',
      currency: 'GBP',
      priceFormatted: '£55.00',
    },
    noirJacket: {
      name: 'Noir jacket',
      handle: 'noir-jacket',
      price: '60.00',
      currency: 'GBP',
      priceFormatted: '£60.00',
    },
    stripedTop: {
      name: 'Striped top',
      handle: 'striped-top',
      price: '50.00',
      currency: 'GBP',
      priceFormatted: '£50.00',
    },
  },

  // Test customer data
  customers: {
    valid: {
      email: 'test.customer@example.com',
      phone: '+447700900123',
      firstName: 'Test',
      lastName: 'Customer',
      address: '123 Test Street',
      address2: 'Apt 4B',
      city: 'London',
      country: 'United Kingdom',
      province: 'England',
      postalCode: 'SW1A 1AA',
    },
    invalidEmail: {
      email: 'invalid-email',
      firstName: 'Test',
      lastName: 'User',
    },
    international: {
      email: 'international@example.com',
      firstName: 'Jean',
      lastName: 'Dupont',
      address: '15 Rue de Paris',
      city: 'Paris',
      country: 'France',
      postalCode: '75001',
    },
  },

  // Discount codes (test values - may not work on live store)
  discounts: {
    valid: 'SAVE10',
    invalid: 'NOTACODE',
    expired: 'EXPIRED2023',
  },

  // Search queries
  search: {
    validProduct: 'jacket',
    partialMatch: 'grey',
    noResults: 'xyznonexistent123',
    specialChars: '<script>alert("xss")</script>',
  },

  // Navigation URLs
  urls: {
    home: '/',
    catalog: '/collections/frontpage',
    cart: '/cart',
    login: '/account/login',
    register: '/account/register',
    search: '/search',
  },

  // Expected page titles
  pageTitles: {
    home: /Sauce Demo|Home/i,
    cart: /Cart|Shopping Cart|Your Cart/i,
    catalog: /Catalog|Collection|Products/i,
  },

  // Quantities for testing
  quantities: {
    default: 1,
    multiple: 3,
    maxAllowed: 99,
    zero: 0,
    negative: -1,
  },

  // Timeouts (ms)
  timeouts: {
    pageLoad: 30000,
    animation: 500,
    cartUpdate: 3000,
    checkout: 30000,
  },
};

/**
 * Generate random email for registration tests
 */
export function generateRandomEmail(): string {
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(7);
  return `test.${random}.${timestamp}@example.com`;
}

/**
 * Generate random string for testing
 */
export function generateRandomString(length: number = 10): string {
  return Math.random().toString(36).substring(2, length + 2);
}
