import { test, expect } from '@playwright/test';
import { SearchPage, HomePage } from '../pages';
import { testData } from '../fixtures/test-data';

/**
 * Search Functionality E2E Tests
 * Tests search, results, and discovery features
 *
 * Generated by: qe-queen-coordinator
 * Priority: P1 (Secondary User Journey)
 */
test.describe('Search Functionality @search', () => {
  test.describe('Search Page', () => {
    test('should display search input on search page', async ({ page }) => {
      const searchPage = new SearchPage(page);

      await searchPage.navigate();
      await searchPage.verifySearchPageLoaded();

      await expect(searchPage.searchInput).toBeVisible();
    });

    test('should show no results message for empty search', async ({ page }) => {
      const searchPage = new SearchPage(page);

      await searchPage.navigate();

      // Empty search should show appropriate message
      const hasNoResults = await searchPage.hasNoResultsMessage();
      expect(hasNoResults).toBe(true);
    });
  });

  test.describe('Search Results', () => {
    test('should return results for valid product search', async ({ page }) => {
      const searchPage = new SearchPage(page);

      await searchPage.navigate();
      await searchPage.searchAndWaitForResults(testData.searchQueries.validProduct);

      const hasResults = await searchPage.hasResults();
      expect(hasResults).toBe(true);
    });

    test('should show no results for non-existent product', async ({ page }) => {
      const searchPage = new SearchPage(page);

      await searchPage.navigate();
      await searchPage.searchAndWaitForResults(testData.searchQueries.noResults);

      const hasResults = await searchPage.hasResults();
      const hasNoResultsMessage = await searchPage.hasNoResultsMessage();

      // Either no results or no results message
      expect(hasResults === false || hasNoResultsMessage === true).toBe(true);
    });

    test('should display relevant results for partial match', async ({ page }) => {
      const searchPage = new SearchPage(page);

      await searchPage.navigate();
      await searchPage.searchAndWaitForResults(testData.searchQueries.partialMatch);

      const results = await searchPage.getResultTitles();

      // If results found, they should contain the search term
      if (results.length > 0) {
        const hasRelevantResult = results.some(title =>
          title.toLowerCase().includes('grey')
        );
        expect(hasRelevantResult).toBe(true);
      }
    });

    test('should navigate to product from search results', async ({ page }) => {
      const searchPage = new SearchPage(page);

      await searchPage.navigate();
      await searchPage.searchAndWaitForResults(testData.searchQueries.validProduct);

      const hasResults = await searchPage.hasResults();

      if (hasResults) {
        await searchPage.clickResult(0);
        expect(page.url()).toContain('/products/');
      }
    });

    test('should maintain search query in URL', async ({ page }) => {
      const searchPage = new SearchPage(page);
      const query = 'jacket';

      await searchPage.navigateWithQuery(query);

      const currentQuery = await searchPage.getCurrentQuery();
      expect(currentQuery).toBe(query);
    });
  });

  test.describe('Search from Homepage', () => {
    test('should access search from homepage header', async ({ page }) => {
      const homePage = new HomePage(page);

      await homePage.navigate();

      // Click search link
      await homePage.searchLink.click();

      // Should be on search page
      expect(page.url()).toContain('/search');
    });
  });

  test.describe('Search Suggestions', () => {
    test('should trigger predictive search on typing', async ({ page }) => {
      const searchPage = new SearchPage(page);

      await searchPage.navigate();
      await searchPage.typeAndWaitForPredictive('jack');

      // Predictive search may or may not be visible depending on implementation
      const suggestions = await searchPage.getPredictiveSuggestions();
      // Just verify it doesn't crash
      expect(Array.isArray(suggestions)).toBe(true);
    });
  });

  test.describe('Search Edge Cases', () => {
    test('should handle special characters in search', async ({ page }) => {
      const searchPage = new SearchPage(page);

      await searchPage.navigate();
      await searchPage.searchAndWaitForResults('jacket & top');

      // Should not crash, page should still be functional
      await expect(searchPage.searchInput).toBeVisible();
    });

    test('should handle very long search queries', async ({ page }) => {
      const searchPage = new SearchPage(page);
      const longQuery = 'a'.repeat(200);

      await searchPage.navigate();
      await searchPage.searchAndWaitForResults(longQuery);

      // Should not crash
      await expect(searchPage.searchInput).toBeVisible();
    });

    test('should handle emoji in search', async ({ page }) => {
      const searchPage = new SearchPage(page);

      await searchPage.navigate();
      await searchPage.searchAndWaitForResults('jacket :)');

      // Should not crash
      await expect(searchPage.searchInput).toBeVisible();
    });

    test('should handle search with only spaces', async ({ page }) => {
      const searchPage = new SearchPage(page);

      await searchPage.navigate();
      await searchPage.searchAndWaitForResults('   ');

      // Should handle gracefully
      const hasNoResults = await searchPage.hasNoResultsMessage();
      // Either no results or treated as empty search
      expect(true).toBe(true);
    });

    test('should clear search and start new search', async ({ page }) => {
      const searchPage = new SearchPage(page);

      await searchPage.navigate();

      // First search
      await searchPage.searchAndWaitForResults('jacket');

      // Clear and new search
      await searchPage.clearSearch();
      await searchPage.searchAndWaitForResults('sandals');

      // Results should be for second search
      const results = await searchPage.getResultTitles();
      if (results.length > 0) {
        const hasRelevantResult = results.some(title =>
          title.toLowerCase().includes('sandal')
        );
        // Results may vary based on store inventory
        expect(Array.isArray(results)).toBe(true);
      }
    });
  });

  test.describe('Search Performance', () => {
    test('should return results within acceptable time', async ({ page }) => {
      const searchPage = new SearchPage(page);

      await searchPage.navigate();

      const startTime = Date.now();
      await searchPage.searchAndWaitForResults('jacket');
      const endTime = Date.now();

      const responseTime = endTime - startTime;

      // Search should complete within 5 seconds
      expect(responseTime).toBeLessThan(5000);
    });
  });
});
