import { test, expect } from '@playwright/test';
import { CheckoutPage, CartPage, ProductPage } from '../pages';
import { TestData } from '../fixtures/test-data';

/**
 * Checkout Flow E2E Tests
 * Test Suite: Proceed to Checkout Flow
 *
 * QE Assessment: sauce-demo.myshopify.com
 * Generated by: QE Queen Coordinator - qe-test-architect domain
 *
 * Coverage:
 * - Checkout page access
 * - Contact information form
 * - Shipping address form
 * - Form validation
 * - Order summary display
 * - Navigation within checkout
 *
 * Note: Actual payment processing is NOT tested (would require
 * test payment gateway credentials)
 */

test.describe('Checkout Flow - Proceed to Checkout', () => {
  let checkoutPage: CheckoutPage;
  let cartPage: CartPage;

  test.beforeEach(async ({ page }) => {
    checkoutPage = new CheckoutPage(page);
    cartPage = new CartPage(page);

    // Add a product to cart before each test
    const productPage = new ProductPage(page);
    await page.goto('/collections/frontpage');
    await page.locator('[class*="product"] a, .grid-product a').first().click();
    await productPage.addToCart();
  });

  test.describe('Checkout Access', () => {
    test('should navigate to checkout from cart', async ({ page }) => {
      await cartPage.goto();
      await cartPage.proceedToCheckout();

      await checkoutPage.assertCheckoutLoaded();
    });

    test('should display order summary on checkout', async ({ page }) => {
      await cartPage.goto();
      await cartPage.proceedToCheckout();

      await expect(checkoutPage.orderSummary).toBeVisible();
    });

    test('should show correct number of items in order summary', async ({ page }) => {
      await cartPage.goto();
      await cartPage.proceedToCheckout();

      const itemCount = await checkoutPage.getOrderItemCount();
      expect(itemCount).toBeGreaterThan(0);
    });

    test('should display order total', async ({ page }) => {
      await cartPage.goto();
      await cartPage.proceedToCheckout();

      await checkoutPage.waitForCheckoutReady();

      const total = await checkoutPage.getOrderTotal();
      expect(total).toBeTruthy();
    });
  });

  test.describe('Contact Information Form', () => {
    test.beforeEach(async ({ page }) => {
      await cartPage.goto();
      await cartPage.proceedToCheckout();
      await checkoutPage.waitForCheckoutReady();
    });

    test('should display email input field', async () => {
      await expect(checkoutPage.emailInput).toBeVisible();
    });

    test('should accept valid email address', async () => {
      await checkoutPage.fillContactInfo(TestData.customers.valid.email);

      // No immediate error for valid email
      const hasErrors = await checkoutPage.hasErrors();
      expect(hasErrors).toBe(false);
    });

    test('should validate email format', async ({ page }) => {
      await checkoutPage.emailInput.fill('invalid-email');
      await checkoutPage.emailInput.blur();

      // Should show validation error or HTML5 validation kicks in
      await page.waitForTimeout(500);

      const emailValidity = await checkoutPage.emailInput.evaluate(
        (el: HTMLInputElement) => el.validity.valid
      );
      expect(emailValidity).toBe(false);
    });
  });

  test.describe('Shipping Address Form', () => {
    test.beforeEach(async ({ page }) => {
      await cartPage.goto();
      await cartPage.proceedToCheckout();
      await checkoutPage.waitForCheckoutReady();
    });

    test('should display all address fields', async () => {
      await expect(checkoutPage.firstNameInput).toBeVisible();
      await expect(checkoutPage.lastNameInput).toBeVisible();
      await expect(checkoutPage.addressInput).toBeVisible();
      await expect(checkoutPage.cityInput).toBeVisible();
      await expect(checkoutPage.countrySelect).toBeVisible();
      await expect(checkoutPage.postalCodeInput).toBeVisible();
    });

    test('should fill shipping address successfully', async () => {
      await checkoutPage.fillContactInfo(TestData.customers.valid.email);
      await checkoutPage.fillShippingAddress({
        firstName: TestData.customers.valid.firstName,
        lastName: TestData.customers.valid.lastName,
        address: TestData.customers.valid.address,
        city: TestData.customers.valid.city,
        country: TestData.customers.valid.country,
        postalCode: TestData.customers.valid.postalCode,
      });

      // Verify fields are filled
      await expect(checkoutPage.firstNameInput).toHaveValue(TestData.customers.valid.firstName);
      await expect(checkoutPage.lastNameInput).toHaveValue(TestData.customers.valid.lastName);
    });

    test('should have country dropdown with options', async () => {
      const options = await checkoutPage.countrySelect.locator('option').count();
      expect(options).toBeGreaterThan(10); // Should have many countries
    });
  });

  test.describe('Form Validation', () => {
    test.beforeEach(async ({ page }) => {
      await cartPage.goto();
      await cartPage.proceedToCheckout();
      await checkoutPage.waitForCheckoutReady();
    });

    test('should require first name', async ({ page }) => {
      await checkoutPage.fillContactInfo(TestData.customers.valid.email);

      // Fill all except first name
      await checkoutPage.lastNameInput.fill(TestData.customers.valid.lastName);
      await checkoutPage.addressInput.fill(TestData.customers.valid.address);
      await checkoutPage.cityInput.fill(TestData.customers.valid.city);
      await checkoutPage.postalCodeInput.fill(TestData.customers.valid.postalCode);

      // Try to continue
      await checkoutPage.continueButton.click();
      await page.waitForTimeout(500);

      // Should show error or remain on same step
      const firstNameValidity = await checkoutPage.firstNameInput.evaluate(
        (el: HTMLInputElement) => el.validity.valid
      );
      expect(firstNameValidity).toBe(false);
    });

    test('should require address', async () => {
      await checkoutPage.fillContactInfo(TestData.customers.valid.email);
      await checkoutPage.firstNameInput.fill(TestData.customers.valid.firstName);
      await checkoutPage.lastNameInput.fill(TestData.customers.valid.lastName);

      // Leave address empty
      await checkoutPage.continueButton.click();

      const addressValidity = await checkoutPage.addressInput.evaluate(
        (el: HTMLInputElement) => el.validity.valid
      );
      expect(addressValidity).toBe(false);
    });

    test('should require postal code', async () => {
      await checkoutPage.fillContactInfo(TestData.customers.valid.email);
      await checkoutPage.fillShippingAddress({
        firstName: TestData.customers.valid.firstName,
        lastName: TestData.customers.valid.lastName,
        address: TestData.customers.valid.address,
        city: TestData.customers.valid.city,
        country: TestData.customers.valid.country,
        postalCode: '', // Empty postal code
      });

      await checkoutPage.continueButton.click();

      const postalValidity = await checkoutPage.postalCodeInput.evaluate(
        (el: HTMLInputElement) => el.validity.valid
      );
      expect(postalValidity).toBe(false);
    });
  });

  test.describe('Checkout Navigation', () => {
    test.beforeEach(async ({ page }) => {
      await cartPage.goto();
      await cartPage.proceedToCheckout();
      await checkoutPage.waitForCheckoutReady();
    });

    test('should allow returning to cart', async ({ page }) => {
      await checkoutPage.returnToCart();

      await expect(page).toHaveURL(/.*cart.*/);
    });

    test('should preserve cart items after returning from checkout', async ({ page }) => {
      await checkoutPage.returnToCart();

      await cartPage.assertHasItems();
    });

    test('should progress to shipping step with valid info', async ({ page }) => {
      await checkoutPage.fillContactInfo(TestData.customers.valid.email);
      await checkoutPage.fillShippingAddress({
        firstName: TestData.customers.valid.firstName,
        lastName: TestData.customers.valid.lastName,
        address: TestData.customers.valid.address,
        city: TestData.customers.valid.city,
        country: TestData.customers.valid.country,
        postalCode: TestData.customers.valid.postalCode,
      });

      await checkoutPage.continueToNextStep();

      // Should progress (either to shipping method or payment)
      await page.waitForTimeout(2000);
      const url = page.url();
      expect(url).toMatch(/checkout/);
    });
  });

  test.describe('Express Checkout Options', () => {
    test.beforeEach(async ({ page }) => {
      await cartPage.goto();
      await cartPage.proceedToCheckout();
      await checkoutPage.waitForCheckoutReady();
    });

    test('should display express checkout section if available', async () => {
      // Express checkout may or may not be configured
      const expressVisible = await checkoutPage.expressCheckout.isVisible({ timeout: 3000 }).catch(() => false);

      if (expressVisible) {
        await expect(checkoutPage.expressCheckout).toBeVisible();
      }
      // Test passes regardless - just checking for presence
    });
  });

  test.describe('International Shipping', () => {
    test('should allow selecting different countries', async ({ page }) => {
      await cartPage.goto();
      await cartPage.proceedToCheckout();
      await checkoutPage.waitForCheckoutReady();

      await checkoutPage.fillContactInfo(TestData.customers.international.email);
      await checkoutPage.countrySelect.selectOption({ label: 'France' });

      // Verify country was selected
      const selectedCountry = await checkoutPage.countrySelect.inputValue();
      expect(selectedCountry).toBeTruthy();
    });
  });

  test.describe('Checkout Error Handling', () => {
    test('should handle network interruption gracefully', async ({ page }) => {
      await cartPage.goto();
      await cartPage.proceedToCheckout();
      await checkoutPage.waitForCheckoutReady();

      // Fill form
      await checkoutPage.fillContactInfo(TestData.customers.valid.email);

      // Simulate slow network
      await page.route('**/*', async route => {
        await new Promise(resolve => setTimeout(resolve, 100));
        await route.continue();
      });

      // Page should still be functional
      await expect(checkoutPage.emailInput).toBeVisible();
    });
  });
});
