import { test, expect } from '@playwright/test';
import { HomePage } from '../pages';
import { TestData } from '../fixtures/test-data';

/**
 * Home Page E2E Tests
 * Test Suite: Browse Products Flow
 *
 * QE Assessment: sauce-demo.myshopify.com
 * Generated by: QE Queen Coordinator - qe-test-architect domain
 *
 * Coverage:
 * - Home page loading and accessibility
 * - Featured products display
 * - Navigation to product pages
 * - Search functionality
 * - Header/footer elements
 */

test.describe('Home Page - Browse Products', () => {
  let homePage: HomePage;

  test.beforeEach(async ({ page }) => {
    homePage = new HomePage(page);
    await homePage.goto();
  });

  test.describe('Page Load and Core Elements', () => {
    test('should load home page successfully', async () => {
      await homePage.assertHomePageLoaded();
    });

    test('should display header with all navigation elements', async ({ page }) => {
      await expect(homePage.header).toBeVisible();
      await expect(homePage.logo).toBeVisible();
      await expect(homePage.cartIcon).toBeVisible();
    });

    test('should display main navigation links', async ({ page }) => {
      await expect(homePage.mainNav).toBeVisible();

      // Verify key navigation items are present
      const navText = await homePage.mainNav.textContent();
      expect(navText?.toLowerCase()).toContain('catalog');
    });

    test('should show cart with zero items initially', async () => {
      const cartCount = await homePage.getCartCount();
      expect(cartCount).toBe(0);
    });

    test('should display footer', async () => {
      await expect(homePage.footer).toBeVisible();
    });
  });

  test.describe('Featured Products Display', () => {
    test('should display featured products section', async () => {
      await homePage.assertFeaturedProductsVisible();
    });

    test('should show at least 3 products on home page', async () => {
      const productCount = await homePage.getFeaturedProductCount();
      expect(productCount).toBeGreaterThanOrEqual(3);
    });

    test('should display product titles', async () => {
      const titles = await homePage.getProductTitles();
      expect(titles.length).toBeGreaterThan(0);

      // Verify expected products are present
      const allTitles = titles.join(' ').toLowerCase();
      expect(allTitles).toMatch(/jacket|top/i);
    });

    test('should display product prices in GBP', async () => {
      const prices = await homePage.getProductPrices();
      expect(prices.length).toBeGreaterThan(0);

      // Verify GBP currency format
      prices.forEach(price => {
        expect(price).toMatch(/£\d+/);
      });
    });

    test('should display product images', async () => {
      await expect(homePage.productImages.first()).toBeVisible();

      // Verify images have valid src
      const src = await homePage.productImages.first().getAttribute('src');
      expect(src).toBeTruthy();
    });
  });

  test.describe('Product Navigation', () => {
    test('should navigate to product page when clicking product', async ({ page }) => {
      await homePage.clickFirstProduct();

      await expect(page).toHaveURL(/.*\/products\/.*/);
    });

    test('should navigate to Grey Jacket product page', async ({ page }) => {
      await homePage.clickProduct('Grey jacket');

      await expect(page).toHaveURL(/.*\/products\/.*/);
      await expect(page.locator('h1')).toContainText(/grey jacket/i);
    });

    test('should navigate to catalog when clicking View All', async ({ page }) => {
      await homePage.viewAllProducts();

      await expect(page).toHaveURL(/.*\/collections\/.*/);
    });
  });

  test.describe('Search Functionality', () => {
    test('should have search functionality available', async () => {
      await expect(homePage.searchIcon).toBeVisible();
    });

    test('should search for products', async ({ page }) => {
      await homePage.search(TestData.search.validProduct);

      await expect(page).toHaveURL(/.*search.*/);
    });

    test('should show results for valid search query', async ({ page }) => {
      await homePage.search('jacket');

      // Verify search page loaded
      await expect(page).toHaveURL(/.*search.*q=jacket.*/i);
    });

    test('should handle search with no results gracefully', async ({ page }) => {
      await homePage.search(TestData.search.noResults);

      // Page should not error
      await expect(page).not.toHaveTitle(/error|500/i);
    });
  });

  test.describe('Cart Icon Interaction', () => {
    test('should navigate to cart page when clicking cart icon', async ({ page }) => {
      await homePage.openCart();

      await expect(page).toHaveURL(/.*\/cart.*/);
    });

    test('should update cart count after adding product', async ({ page }) => {
      // Go to a product and add it
      await homePage.clickFirstProduct();
      await page.locator('button[name="add"], [data-add-to-cart]').first().click();

      // Wait for cart update
      await page.waitForTimeout(1000);

      // Cart count should update
      const cartBubble = page.locator('.cart-count, .cart-link__bubble, [data-cart-count]');
      await expect(cartBubble).toBeVisible({ timeout: 5000 });
    });
  });

  test.describe('Responsive Design', () => {
    test('should be accessible on mobile viewport', async ({ page }) => {
      await page.setViewportSize({ width: 375, height: 667 });
      await page.reload();

      await homePage.assertHomePageLoaded();
      await expect(homePage.header).toBeVisible();
    });

    test('should be accessible on tablet viewport', async ({ page }) => {
      await page.setViewportSize({ width: 768, height: 1024 });
      await page.reload();

      await homePage.assertHomePageLoaded();
    });
  });
});
