#!/bin/bash
# AQE v3 Worker Daemon Startup Script
# Generated by aqe init
# Starts the MCP server with background workers enabled

# Get directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Navigate up from .agentic-qe/workers to project root
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
WORKERS_DIR="$PROJECT_ROOT/.agentic-qe/workers"
PID_FILE="$WORKERS_DIR/daemon.pid"
LOG_FILE="$WORKERS_DIR/daemon.log"

# Check if already running
if [ -f "$PID_FILE" ]; then
  PID=$(cat "$PID_FILE")
  if kill -0 "$PID" 2>/dev/null; then
    echo "Daemon already running (PID: $PID)"
    exit 0
  fi
fi

echo "[$(date)] Starting AQE v3 Worker Daemon..." >> "$LOG_FILE"

# Set environment for learning and workers
export AQE_PROJECT_ROOT="$PROJECT_ROOT"
export AQE_LEARNING_ENABLED=true
export AQE_WORKERS_ENABLED=true
export AQE_HTTP_PORT=0

# Find the best way to run aqe-mcp
MCP_CMD=""
if [ -f "$PROJECT_ROOT/node_modules/.bin/aqe-mcp" ]; then
  MCP_CMD="$PROJECT_ROOT/node_modules/.bin/aqe-mcp"
elif [ -f "$PROJECT_ROOT/node_modules/agentic-qe/v3/dist/mcp/bundle.js" ]; then
  MCP_CMD="node $PROJECT_ROOT/node_modules/agentic-qe/v3/dist/mcp/bundle.js"
elif [ -f "$PROJECT_ROOT/node_modules/.bin/aqe" ]; then
  # Use aqe CLI with mcp subcommand
  MCP_CMD="$PROJECT_ROOT/node_modules/.bin/aqe mcp"
elif command -v aqe-mcp &> /dev/null; then
  MCP_CMD="aqe-mcp"
elif command -v aqe &> /dev/null; then
  # Use global aqe CLI with mcp subcommand
  MCP_CMD="aqe mcp"
else
  # Fallback to npx - aqe CLI has mcp subcommand
  MCP_CMD="npx --yes agentic-qe mcp"
fi

echo "[$(date)] Using MCP command: $MCP_CMD" >> "$LOG_FILE"

# Start the MCP server with workers
cd "$PROJECT_ROOT"
nohup $MCP_CMD >> "$LOG_FILE" 2>&1 &
DAEMON_PID=$!

# Save PID
echo $DAEMON_PID > "$PID_FILE"
echo "[$(date)] Daemon started with PID: $DAEMON_PID" >> "$LOG_FILE"

echo "AQE v3 Worker Daemon started (PID: $DAEMON_PID)"
echo "Log file: $LOG_FILE"
echo ""
echo "To stop: kill $DAEMON_PID"
echo "To view logs: tail -f $LOG_FILE"
