#!/bin/bash
# AQE v3 Worker Daemon Stop Script
# Generated by aqe init

# Get directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Navigate up from .agentic-qe/workers to project root
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
WORKERS_DIR="$PROJECT_ROOT/.agentic-qe/workers"
PID_FILE="$WORKERS_DIR/daemon.pid"

if [ -f "$PID_FILE" ]; then
  PID=$(cat "$PID_FILE")
  if kill -0 "$PID" 2>/dev/null; then
    echo "Stopping daemon (PID: $PID)..."
    kill "$PID"
    rm -f "$PID_FILE"
    echo "Daemon stopped"
  else
    echo "Daemon not running (stale PID file)"
    rm -f "$PID_FILE"
  fi
else
  echo "No PID file found - daemon may not be running"
fi
